### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by mateit-cloudware** [smartstore/Smartstore#1007]
**Describe the bug**
We are trying to push data via API into SmartStore.net and receive a CORS Error

Here the error message:[]()![Screenshot_20240209_072611_ChatGPT.jpg](https://github.com/smartstore/Smartstore/assets/69690256/97dd07d6-4797-4af6-ad6c-a132bd4490cc)

Can you please help with it?

**Comment by mgesing** [comment]
CORS support for the API will come with the next version 5.2.0. See [changelog](https://github.com/smartstore/Smartstore/blob/main/changelog.md). It is not included in the current version 5.1.0.
