### ISSUE TITLE
install failed :Mysql  Type  Setup failed: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1019]
**install failed**

Setup failed: Specified key was too long; max key length is 1000 bytes

- Mysql
- **version**: Smartstore.Community.5.1.0.win-x64

![image](https://github.com/smartstore/Smartstore/assets/39150678/4e769b35-cf3e-4b13-ad1b-56fc18b8b2ce)

**Comment by zihniartar** [comment]
I cannot reproduce the error on a Windows server with IIS 10 and MySQL 8.0.36.
