### ISSUE TITLE
Don't render payment buttons in OffCanvasCart if there are mandatory checkout attributes

### ISSUE THREAD

**Issue by Michael-Herzog** [smartstore/Smartstore#1023]
Enhance MiniShoppingCartModel with a value which indicates whether Buttons should be rendered and apply here:
Smartstore\src\Smartstore.Web\Views\ShoppingCart\Partials\OffCanvasShoppingCart.cshtml Line 179 

TBD: What about checkout attributes that have a charge? Should we enforce saving them first before making payments?

**Comment by mgesing** [comment]
> TBD: What about checkout attributes that have a charge? Should we enforce saving them first before making payments?

This is the job of the payment plugin. If it already creates a payment transaction on the cart page, it must first call `IShoppingCartService.SaveCartDataAsync` to save the data selected on the shopping cart page (including checkout attributes).
