### ISSUE TITLE
Linux X64 installation failed! In theory, it should be installable.

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1040]
**Linux X64 installation failed! In theory, it should be installable.**
- in AlmaLinux  9.3 OS
- **AlmaLinux release 9.3** (Shamrock Pampas Cat)
- **SELinux** : disabled
```bash
[root@QuickTest ~]# sestatus
SELinux status:                 disabled
```

![image](https://github.com/smartstore/Smartstore/assets/39150678/f64665a1-c277-4820-965d-4f51839a2f82)

- In Ubuntu 23.10 OS

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic
```
I also tested the installation of this system, but it was not successful either.

**Comment by zihniartar** [comment]
this is how I do it under NGINX:

chown -R www-data /var/www/smartstore/ &&
chgrp -R www-data /var/www/smartstore/ &&
chmod -R 750 /var/www/smartstore/ &&
chmod g+s /var/www/smartstore/ &&
chmod -R g+w /var/www/smartstore/App_Data &&
chmod -R g+w /var/www/smartstore/Modules &&
chmod +x /var/www/smartstore/Smartstore.Web

**Comment by AtlantisDe** [comment]
> this is how I do it under NGINX:
> 
> chown -R www-data /var/www/smartstore/ && chgrp -R www-data /var/www/smartstore/ && chmod -R 750 /var/www/smartstore/ && chmod g+s /var/www/smartstore/ && chmod -R g+w /var/www/smartstore/App_Data && chmod -R g+w /var/www/smartstore/Modules && chmod +x /var/www/smartstore/Smartstore.Web

**  I've tested it. It didn't work. There should be a problem with the permissions.**

**Comment by stefanmuellerdo** [comment]
- please post a `ls -l` from your installation directory
- post your NGINX Configuration
- post also the interesting part from your NGINX error log
- is SELinux enabled? --> problem zone
- has everything the correct execute permissions set?

**Comment by zihniartar** [comment]
> > this is how I do it under NGINX:
> > chown -R www-data /var/www/smartstore/ && chgrp -R www-data /var/www/smartstore/ && chmod -R 750 /var/www/smartstore/ && chmod g+s /var/www/smartstore/ && chmod -R g+w /var/www/smartstore/App_Data && chmod -R g+w /var/www/smartstore/Modules && chmod +x /var/www/smartstore/Smartstore.Web
> 
> ** I've tested it. It didn't work. There should be a problem with the permissions.**

I assume that you have adjusted the paths

`var/www/smartstore/`

and if you absolutely want to use the root user, you must also adjust this in the command

`www-data`

**Comment by AtlantisDe** [comment]
@stefanmuellerdo @zihniartar I have successfully installed it on Ubuntu 22.04.4 LTS system.

- I have successfully installed it on **Ubuntu 22.04.4 LTS** system.
- Permission usage:**775**
- mysql  Ver 8.0.36-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

- AlmaLinux OS : It failed when I tested it, so I stopped using that OS **(AlmaLinux release 9.3 (Shamrock Pampas Cat))** I have time, I will come back and continue testing.  It keeps prompting me about permission issues

- Supervisor : I run it using the **root** user.

```bash
/root/.dotnet/dotnet /www/wwwroot/TestStore/Smartstore.Web.dll --urls 'http://localhost:1001'
```

- Config file

```bash
[program:TestSmartStoreApp]
command=/root/.dotnet/dotnet /www/wwwroot/TestStore/Smartstore.Web.dll --urls 'http://localhost:1001'
directory=www/wwwroot/TestStore/
autorestart=true
startsecs=3
startretries=3
stdout_logfile=/www/server/panel/plugin/supervisor/log/QDS.out.log
stderr_logfile=/www/server/panel/plugin/supervisor/log/QDS.err.log
stdout_logfile_maxbytes=2MB
stderr_logfile_maxbytes=2MB
user=root
priority=999
numprocs=1
process_name=%(program_name)s_%(process_num)02d
```

- Nginx: Finally use Nginx for Reverse proxy
```bash

```

![image](https://github.com/smartstore/Smartstore/assets/39150678/8a805553-fc54-4b92-90e5-d6513a93122b)

**Comment by stefanmuellerdo** [comment]
* Running this stuff as root is bad practice and insecure, don't do it unless for internal testing on an isolated local system (and even then, don't do it).

* Again, please provide the output of ls -l for the installation directory and the requested log files. Should be no security problem. I have a feeling that you have nothing sensitive in there, as you are working as root. 

* Your last screenshot with this click stuff control is not sufficient. Maybe the clicktool failed somehow? Do you have some security tools like SElinunx running? Again, just provide that ls -l output so we can take a look at that. Thank you.

**Comment by stefanmuellerdo** [comment]
@AtlantisDe is this still an open issue for you? Please close if fixed. Thanks.

**Comment by AtlantisDe** [comment]
@stefanmuellerdo Temporarily closed! When you have time, test this system again.

The current system used is successful: Ubuntu 23.10
OS:AlmaLinux release 9.3 Still waiting for testing. When your next version comes out, I will help test it.
