### ISSUE TITLE
use Nginx for Reverse proxy ,When an error is encountered, the redirect address is not processed correctly

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1044]
**use Nginx for Reverse proxy**
- use Nginx for Reverse proxy ,When an error is encountered, the redirect address is not processed correctly

**Config Like**
```c#
// Reverse proxy
Shop URL:http://test.com/
HOST values:test.com
```

**.net run**
```c#
dotnet Smartstore.Web.dll --urls "http://localhost:1005"
```

**Screenshots**
![image](https://github.com/smartstore/Smartstore/assets/39150678/4fa43d40-206a-407a-a187-ec1db6dd66ef)

**Comment by mgesing** [comment]
Do you have **[ReverseProxy](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Web/appsettings.Development.json#L21)** in appsettings.Development.json enabled? I have often used and tested this successfully with Ngrok.

**Comment by AtlantisDe** [comment]
@mgesing I have closed it now. I observed it and I forgot how to reproduce this situation.

```json
    "ReverseProxy": {
      // "true" enables the ForwardedHeadersMiddleware.
      "Enabled": false,
```

**Comment by AtlantisDe** [comment]
### This abnormal situation still occurs.

- eg:  Visit this address

```shell

https://www.test.com/admin/
```

- Internally redirected to a fixed address

```shell
Status Code:302 Found

Location:http://localhost/login/?returnUrl=%2Fadmin%2F

```

![image](https://github.com/smartstore/Smartstore/assets/39150678/6085a0b5-b995-4812-bd8b-cc241c309087)
