### ISSUE TITLE
I think there are serious flaws in the guest character (Role) design.

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1051]
🙋 **I think there are serious flaws in the guest character design.**

💥 I have tested and tried tens of thousands of times, sending data in the form of packets, databases, and records will create a lot of data as guests.

**Specific steps**

❣️ I won't go into details here, I'm worried that someone might use it for attack.

**help**

🚨 Is there a plan or setting that can be turned on and off?

```c#
// I found this, I will continue to test it...
CommonSettings.MaxGuestsRegistrationAgeInMinutes
```

**Comment by stefanmuellerdo** [comment]
https://github.com/smartstore/Smartstore/blob/main/CONTRIBUTING.md#reporting-a-security-issue :

> Please report any sensitive, critical, or urgent vulnerabilities by using our [contact form](https://smartstore.com/en/contact) saying you need to communicate an important security issue.
> 
> After assessing the issue, we will work out how we will handle the matter and let you know how to proceed. If the vulnerability is neither sensitive, critical, or urgent, please just create a [new issue](https://github.com/smartstore/Smartstore/issues/new/choose) as per normal.

**Comment by AtlantisDe** [comment]
OKay
