### ISSUE TITLE
Remove empty line for art-delivery-info

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1059]
Hi,

blank line is created when art-delivery-info is empty... Could conditions be added with sm-if?

`sm-if="Model.IsShippingEnabled && delivery.ShowDeliveryTime"`

```
<div sm-if="Model.IsShippingEnabled && delivery.ShowDeliveryTime" class="art-delivery-info">
    @if (delivery.StatusLabel.HasValue())
    {
        <span class="delivery-time" title="@T("Products.DeliveryTime") @delivery.StatusLabel"
              attr-style='(delivery.DisplayDeliveryTimeAccordingToStock, "color:" + delivery.DeliveryTimeHexValue)'>
            <i class="fa fa-circle delivery-time-status"></i>
            <span dir="auto">@delivery.StatusLabel</span>
        </span>
    }
    @if (delivery.DeliveryTimeDate.HasValue())
    {
        <span class="delivery-date-block" title="@T("Products.DeliveryDate") @delivery.DeliveryTimeDate.RemoveHtml()">
            <span sm-if="delivery.StatusLabel.IsEmpty()">@T("Products.DeliveryDate")</span>
            <span class="delivery-date" dir="auto">@Html.Raw(delivery.DeliveryTimeDate)</span>
        </span>
    }
</div>
```

**Comment by mgesing** [comment]
It looks to me as if this has been done quite deliberately so that the information of each product is aligned exactly horizontally.

**Comment by suatsuphi** [comment]
there is a parametre for it that "Presentation of delivery times" (do not display) 
if do not display is selected all height will be equal.

so  `sm-if="shoppingCartSettings.DeliveryTimesInShoppingCart != DeliveryTimesPresentation.None" `

Otherwise there will be an unnecessary blank space all over the website when the parameter is do not display
