### ISSUE TITLE
duplicate notify message

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1080]
Hi,

there is a minor error for notify message

![image](https://github.com/smartstore/Smartstore/assets/20780272/dc6296cc-9268-4712-a6da-6db1bf602115)

**Comment by mgesing** [comment]
Not reproducible.

**Comment by suatsuphi** [comment]
now, I downloaded the original project and ran it. problem persists

**Comment by suatsuphi** [comment]
first I cleared the cache and it didn't fix it. then I reset the whole browser (edge) and now it's fixed. how can this be? :)
