### ISSUE TITLE
How does limited to customer roles work?

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1104]
Hi,

How does limited to customer roles work? page can be viewed restriction is not working ?

https://localhost:44325/aboutus/ 

![image](https://github.com/smartstore/Smartstore/assets/20780272/d1d21ca4-4058-4c91-a0be-07114244d63e)

**Comment by mgesing** [comment]
If you limit to guests _and_ registered users, then you are effectively not limiting at all, because practically every user is assigned one of the two roles.

**Comment by suatsuphi** [comment]
In Store it blocks the selected stores... On the user, it only allows the selected user!
