### ISSUE TITLE
Sorting for price does not use discounted prices but the original prices

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#1137]
**Describe the bug**
We have a category for our special sale products with discounts ranging from 10% to 40%.
But if we sort by price (up or down), the sorting does not sort by effective price but original price or the product.

Reproduced it in demo shop.

![image](https://github.com/smartstore/Smartstore/assets/2128945/77092eca-55fc-4356-8733-14636dd2c6e1)

**Comment by Algorithman** [comment]
Instead of 
```
            else if (sorting.FieldName == names.Price)
            {
                query = OrderBy(query, x => x.Price, sorting.Descending);
            }
```

I came up with this snippet which works for me, but it certainly needs more tests. I only applied one discount at a time.
And it can (probably) be improved.
```
                if (sorting.Descending)
                {
                    query = query
                        .OrderByDescending(x =>
                            x.HasDiscountsApplied && x.AppliedDiscounts.Any(discount =>
                                (!discount.StartDateUtc.HasValue || discount.StartDateUtc.Value <= DateTime.UtcNow) &&
                                (!discount.EndDateUtc.HasValue || discount.EndDateUtc.Value >= DateTime.UtcNow))
                                ? x.Price - x.AppliedDiscounts
                                    .Where(discount =>
                                        (!discount.StartDateUtc.HasValue || discount.StartDateUtc.Value <= DateTime.UtcNow) &&
                                        (!discount.EndDateUtc.HasValue || discount.EndDateUtc.Value >= DateTime.UtcNow))
                                    .Max(discount =>
                                        discount.UsePercentage
                                            ? x.Price * discount.DiscountPercentage / 100m
                                            : discount.DiscountAmount)
                                : x.Price);
                }
                else
                {
                    query = query
                        .OrderBy(x =>
                            x.HasDiscountsApplied && x.AppliedDiscounts.Any(discount =>
                                (!discount.StartDateUtc.HasValue || discount.StartDateUtc.Value <= DateTime.UtcNow) &&
                                (!discount.EndDateUtc.HasValue || discount.EndDateUtc.Value >= DateTime.UtcNow))
                                ? x.Price - x.AppliedDiscounts
                                    .Where(discount =>
                                        (!discount.StartDateUtc.HasValue || discount.StartDateUtc.Value <= DateTime.UtcNow) &&
                                        (!discount.EndDateUtc.HasValue || discount.EndDateUtc.Value >= DateTime.UtcNow))
                                    .Max(discount =>
                                        discount.UsePercentage
                                            ? x.Price * discount.DiscountPercentage / 100m
                                            : discount.DiscountAmount)
                                : x.Price);
                }

```

**Comment by mgesing** [comment]
This could be challenging to solve completely (including MegaSearch) because therefore all prices for all published currencies have to be calculated and saved in the search index. The above sorting only applies to the standard search via Linq. It's only a "half solution" because price filtering is also affected. Several of the fields do not have a database index, which can affect performance.

**Comment by Algorithman** [comment]
My snippet also only sorts by product applied discounts, category discounts are not taken into account.
But since we only use product discounts (10% 20% 30% 40% 50%) and no megasearch, it's enough for us. (category discounts probably have to be done in-memory anyways, which opens another can of troubles)

But overall I think it is something which should be addressed, since sort by price is often used by customers looking through sale categories or weekly specials.

**Comment by mgesing** [comment]
I have created a new [issue](https://github.com/smartstore/Smartstore/issues/1211) to at least take the special price into account when sorting.
