### ISSUE TITLE
Postback happens when using RuleFor with When in FluentValidation

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1144]
Hi,

Postback happens when using RuleFor with When in FluentValidation... Is it normal ?

```
RuleFor(x => x.Delay).NotNull().WithMessage(T("Plugins.Smartstore.BT.PageBuilder.NotEmptyValidator"))
     .When(x => x.Zone != null);
```

solution: 

```
RuleFor(x => x).SetValidator(new WithWhenConditionValidator(T))
                        .When(x => x.Zone != null);
```

```
public class WithWhenConditionValidator : AbstractValidator<PageItemModel>
{
    public WithWhenConditionValidator(Localizer T)
    {
        RuleFor(x => x.Delay).NotNull();
    }
}
```

**Comment by muratcakir** [comment]
> Postback happens when using RuleFor with When in FluentValidation... Is it normal ?

Yes, it is. Because `When()` can contain complex expressions that may not be processable on the client-side.

**Comment by suatsuphi** [comment]
There are two problems when I use "when" for postback. 

1- html b tag is not processed
2- is-invalid class is not added to input. Instead input-validation-error is added.

![image](https://github.com/user-attachments/assets/9642e661-9759-4983-815c-9004883d538d)

**Comment by suatsuphi** [comment]
1- html b tag is not processed

`public class PageObjectModelValidator : SmartValidator<PageObjectModel> `
or 
`public class PageObjectModelValidator : AbstractValidator<PageObjectModel>`

 ```
When(x => (x.Zone?.Contains("PopupWindow")).GetValueOrDefault(false), () =>
 {
     RuleFor(x => x.Delay).NotEmpty();
 });
```

or

```
 When(x => (x.Zone?.Contains("PopupWindow")).GetValueOrDefault(false), () =>
 {
     RuleFor(x => x.Delay).NotEmpty().WithMessage(T("Plugins.Smartstore.BT.PageBuilder.NotEmptyValidator"));
 });
```

 I use model's validator and get the same result

![image](https://github.com/user-attachments/assets/b76f15f0-aaaf-4f6a-8389-330fcc189341)

**Comment by suatsuphi** [comment]
for testing purposes `@Html.ValidationMessageFor(m => m.Delay).ToHtmlString().Value`

```
 <div class="adminRow">
     <div class="adminTitle">
         <smart-label asp-for="Delay" />
     </div>
     <div class="adminData">
         <editor asp-for="Delay" />
         <span asp-validation-for="Delay"></span>
         @Html.ValidationMessageFor(m => m.Delay).ToHtmlString().Value
     </div>
 </div>
```

result :

<b>Delay</b> cannot be empty
<span class="field-validation-error" data-valmsg-for="Delay" data-valmsg-replace="true">&lt;b&gt;Bekleme S&#xFC;resi&lt;/b&gt; cannot be empty</span>

**Comment by muratcakir** [comment]
Just `@Html.ValidationMessageFor(m => m.Delay)` is sufficient.

**Comment by suatsuphi** [comment]
I tried this. Because I use when (in validator), the characters in the html code in the incoming message <b> turn into this &lt;b&gt;

because of postback

**Comment by suatsuphi** [comment]
Also I cant use this `@Html.Raw(@Html.ValidationMessageFor(m => m.Delay)) ` or `@Html.Raw(Html.ValidationMessageFor(m => m.Delay))`

result Microsoft.AspNetCore.Mvc.Rendering.TagBuilder

**Comment by suatsuphi** [comment]
` <span>@Html.Raw(ViewData.ModelState["Delay"]?.Errors.FirstOrDefault()?.ErrorMessage)</span>` 

If I use it this way, my question is solved. 

Source of the problem asp-validation-for="Delay"


`<span asp-validation-for="Delay"></span>`

**Comment by suatsuphi** [comment]
the same problem in `<div asp-validation-summary="All"></div> `

This problem occurs when postback.

**Comment by suatsuphi** [comment]
solution to the problem


```
$(document).ready(function () {
    $('.field-validation-error').each(function () {
        $(this).html($(this).text());
    });

    $('.validation-summary-errors ul li').each(function () {
        $(this).html($(this).text());
    });
});
```

**Comment by suatsuphi** [comment]
chatgpt suggested something like this... replaces the message that comes with ajaxComplete. 

```
    $(document).ajaxComplete(function () {
        $('.field-validation-error').each(function () {
            var rawHtml = $(this).html();
            $(this).html(rawHtml.replace(/&lt;/g, '<').replace(/&gt;/g, '>'));
        });
        $('.validation-summary-errors').each(function () {
            var rawHtml = $(this).html();
            $(this).html(rawHtml.replace(/&lt;/g, '<').replace(/&gt;/g, '>'));
        });
    });
```

**Comment by suatsuphi** [comment]
a similar situation exists for TopicValidator... If html tag (b and strong) is used in **Admin.ContentManagement.Topics.Validation.NoPasswordAllowed**, it is not rendered
