### ISSUE TITLE
Media Manager: Context Menu Not Accessible in Empty Folder

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#1145]
Media Manager: Context Menu Not Accessible in Empty Folder

**Description:**
In Smartstore 5.2a (18.7.2024) Media Manager, the right-click context menu is not accessible when a folder is empty. This issue prevents users from pasting images from the clipboard via the "Insert" option in the context menu.

**Steps to Reproduce:**
1. Open Media Manager in Smartstore 5.2a.
2. Navigate to an empty folder.
3. Attempt to right-click within the empty folder space.

**Expected Behavior:**
The right-click context menu should appear, allowing users to paste images from the clipboard via the "Insert" option.

**Actual Behavior:**
No context menu is displayed in an empty folder, preventing the paste functionality.

**Workaround:**
The context menu can be accessed by ensuring there is at least one file in the folder. Right-clicking on the existing file will display the context menu.

**Attachments:**
Screenshot demonstrating the issue and the workaround.

![media-manager-context-menu](https://github.com/user-attachments/assets/b940a533-a2d7-41bb-ba0f-28d99391ade6)

**Environment:**
- Version: Smartstore 5.2a
- Date: 18.7.2024

**Additional Notes:**
This issue affects the usability of the Media Manager, particularly when users need to paste images into new or currently empty folders.

---

Please address this issue to improve the Media Manager's functionality. Thank you.

**Comment by stefanmuellerdo** [comment]
Keyboard Shortcuts crtl c ctrl v did not work on current MacOS / Safari

**Comment by muratcakir** [comment]
I admit, that's not very intuitive. But the folder's context menu also contains all the relevant menu items.

**Comment by stefanmuellerdo** [comment]
[like]  Stefan Müller reacted to your message:
________________________________
