### ISSUE TITLE
New 5.1.0.x build faulty - HTTP error when updating application

### ISSUE THREAD

**Issue by ThiloGHL** [smartstore/Smartstore#1146]
Hi,

I hope someone can help me with this issue. I have run the build script build.win-x64.cmd with the current 5.1.0.x branch and tried to overwrite the current smartstore with it, but then I get a _HTTP Error 500.30 - ASP.NET Core app failed to start_. The event log shows the following:

> Application '/LM/W3SVC/3/ROOT' with physical root 'C:\inetpub\sites\smartstoreDev\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.TypeLoadException: Method 'LoadAsync' in type 'Smartstore.MegaSearch.Lucene.LuceneMetadataStorage' from assembly 'Smartstore.MegaSearch, Version=5.0.5.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Smartstore.MegaSearch.Startup.ConfigureServices(IServiceCollection services, IApplicationContext appContext)
   at Smartstore.Engine.EngineStarter`1.ConfigureServices(IServiceCollection services) in C:\Lokal Bearbeiten\Smartstore_Projekt\Smartstore\src\Smartstore\Engine\EngineStarter.cs:line 185
   at Smartstore.Engine.SmartEngine.EngineStarter.ConfigureServices(IServiceCollection services) in C:\Lokal Bearbeiten\Smartstore_Projekt\Smartstore\src\Smartstore\Engine\SmartEngine.cs:line 156
   at Program.<Main>$(String[] args) in C:\Lokal Bearbeiten\Smartstore_Projekt\Smartstore\src\Smartstore.Web\Program.cs:line 95
   at Program.<Main>(String[] args)

If I switch back to the previously used version and build and overwrite again, it no longer works (but the error in the event log is different). I still have the build from when it still worked and when I overwrite the files with it, the application runs again. So what is going wrong with the build?
I did not change any config but to make sure everything is correct, I've downloaded all files again.

Best regards

Thilo

**Comment by mgesing** [comment]
It sounds like you are mixing different versions. The core with a more recent version from branch 5.1.0.x and a deployment that consists at least in part of 5.0.5.0.

**Comment by ThiloGHL** [comment]
Ok, how can this happen and how to solve this?
We're currently using version 5.1.0.0 and have problems with a bug. According to the Smartstore support this bug has been fixed with a hotfix in 5.1.0.x so we need to update. But since we made some custom changes, we need to build and update to the new version by ourself but now are facing this problem even if we build any version without our custom changes.

**Comment by mgesing** [comment]
Hotfixes are provided via the [marketplace](https://community.smartstore.com/index.php?/files/category/33-service-packs-hotfixes/).

For individual adjustments to the source code (version derived from Smartstore), it is recommended to use an own GitHub fork, which can be synchronized with the relevant branch if required. For version 5.1.0, this would be branch 5.1.0.x. For plugins that are not open source (such as MegaSearch), the Enterprise Edition is required to gain access to their source code.

**Comment by ThiloGHL** [comment]
Ok, thank you. So probably the plugin updates are missing?

Yes, we use an own fork of this GitHub project. I have downloaded the official hotfix and replaced the files with the hotfix files. The application works with the hotfix.
I have then overwritten the files with our own build of 5.1.0.x again but copied the Modules folder from the hotfix but it's still not working. Is there any other relevant file to update the modules only?
We don't need access to the plugin source code.

**Comment by ThiloGHL** [comment]
Any further ideas what the problem could be?
We can't get the current 5.1.0.x build to work when we build it ourself. Overwriting the plugin files with the files from the official version does not solve the problem.

**Comment by ThiloGHL** [comment]
I have just tried to replace the Smartstore Core files only since I've only made changes to Smartstore Core.
But as soon as I replace Smartstore.Core.dll and Smartstore.Core.pdb I get the error:

> Application '/LM/W3SVC/3/ROOT' with physical root 'C:\inetpub\sites\smartstoreDev\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.TypeLoadException: Method 'LoadAsync' in type 'Smartstore.MegaSearch.Lucene.LuceneMetadataStorage' from assembly 'Smartstore.MegaSearch, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Smartstore.MegaSearch.Startup.ConfigureServices(IServiceCollection services, IApplicationContext appContext)
   at Smartstore.Engine.EngineStarter`1.ConfigureServices(IServiceCollection services)
   at Smartstore.Engine.SmartEngine.EngineStarter.ConfigureServices(IServiceCollection services)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
Does this mean the Plugin is integrated into Smartstore Core and I need access to another code base?

**Comment by Michael-Herzog** [comment]
This will probably be caused by an outdated implementation of MegaSearch. Since 5.1.0.x is the latest code inclusive hotfixes you also need the latest MegaSearch plugin. We'll also answer the ticket you've created in our ticket system to transmit the latest files to you.
