### ISSUE TITLE
Feature request: Natural sorting for product attributes

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#1158]
### Feature Request: Natural Sorting for Product Attributes

**Summary:**
Implement *natural sorting* for product attributes in Smartstore to ensure a more intuitive and user-friendly automatic standard sorting order for alphanumeric strings. without having to set up the sort order manually in the attribute details.

https://en.wikipedia.org/wiki/Natural_sort_order

![autosorted](https://github.com/user-attachments/assets/63436ea6-7ec7-4c41-a0ec-51f12b3d1d51)

**Description:**
Currently, product attributes in Smartstore are sorted using standard lexicographical order. 

This can lead to unintuitive sorting results, especially when dealing with strings containing numbers. 

For instance, the current sorting might order "1", "11", "2", which is not ideal for user experience. 

Natural sorting would arrange these values as "1", "2", "11", reflecting a more logical numerical progression.

**Benefits:**
- Improved user experience: Users will find it easier to navigate and find items with correctly ordered attributes.
- Enhanced data presentation: More intuitive sorting will make product listings and attribute filtering more readable and logical.
- Competitive advantage: This feature can be highlighted as a user-centric enhancement, setting Smartstore apart from competitors.

Natural Sorting is standard in modern OS, like MacOS file lists. https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemDetails/FileSystemDetails.html

Has been reported by a store operator & ERP partner.

**Comment by stefanmuellerdo** [comment]
thanks !!!

**Comment by mgesing** [comment]
Some notes. `NATURAL_SORT_KEY` is not supported by T-SQL. Only to be used in certain cases for _materialized_ data. Should be avoided on database side for performance reasons. [Link](https://www.sqlservercentral.com/forums/topic/natural-sort-order/page/2).
