### ISSUE TITLE
[Question] Backend customizations

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#1171]
**Is your feature request related to a problem? Please describe.**
Since we do have special data attached to our products (fully customer changeable), we store them in OrderItem.RawAttributes (which works just fine for everything in the frontend).

But in the backend I have 2 problems:
1. Often the backend only calls the `MiniMapper` to map the data (for example `OrderItem `-> `OrderModel.OrderItemModel` in `CreateOrderItemsModels` in the `OrderController`). This makes it impossible to map our custom data in the backend, since the simple mapping via `MiniMapper` does not call the whole mapper stack.
2. How can I make adjustments to backend cshtml files in my module? I tried to use the same folder structure (for example `Areas/Admin/Views/Order/_Edit.Info.cshtml`) but I can't make the backend use my cshtml implementation, so I'm stuck at the moment with changing it in Smartstore.Web project (which I don't really want to do, I would like to leave it as pristine as I can). We would like for example to show our custom data in the grid etc, so we can see at a glance what data the customer entered.

In my opinion, direct calls to the `MiniMapper` should not be made.
The `MapperFactory` should be the only one calling the `MiniMapper` as a default mapping and then call the whole stack of `IMapper<TFrom,TTo>`'s.

**Comment by mgesing** [comment]
> How can I make adjustments to backend cshtml files in my module?

I don't think the entire view can be swapped from a plugin location. At least I haven't seen it yet. The content of a backend view can be expanded via widget zones. If a suitable one is missing, a new one must be added. This is the intended procedure.

**Comment by Michael-Herzog** [comment]
Hi,
another approach which I would use:
I would present extra data on the product level via an own tab as explained here:
https://smartstore.gitbook.io/developer-guide/compose/modules/examples/adding-tabs
For extra actions in the product grid you could use a filter like this:

        public void OnResultExecuting(ResultExecutingContext context)
        {
            if (context.Result.IsHtmlViewResult())
            {
                var routeData = context.RouteData.Values;
                var action = routeData.GetActionName();

                var orderId = (routeData["id"] as string).ToInt();
                _widgetProvider.Value.RegisterViewComponent<AdminToolbarViewComponent>(
                    new[] { "datagrid_toolbar_omega", "admin_button_toolbar_after" },
                    new { action, orderId });
            }
        }

And if you want to present custom data in a product grid I'd recommend building your own grid in the configuration view of your module.

Regards,
Michael
