### ISSUE TITLE
EmailReminder | Scheduled Tasks doesn't work

### ISSUE THREAD

**Issue by schraufi** [smartstore/Smartstore#1181]
Hello, the **scheduled tasks** don't work with the **Email Reminder** plugin.

Executing them manually works.

LG, Alex

![Screenshot 2024-09-20 092643](https://github.com/user-attachments/assets/03c083fb-4eb3-4fc4-87e8-30ed5a0a1241)

**Comment by mgesing** [comment]
Works for me. Maybe check the job execution tomorrow at 12:00 AM.

**Comment by schraufi** [comment]
The task was initially scheduled to run at 12:00 AM (midnight). However, a server restart occurs at that time, so the execution time has been changed to 4:00 PM. Since then, the task has been running smoothly.
