### ISSUE TITLE
Image Upload Fails After Selecting 'Replace' or 'Rename' for Duplicate Files

### ISSUE THREAD

**Issue by amazing12349** [smartstore/Smartstore#1185]
**Describe the bug**
When uploading an image with the same name, the "Replace or Skip" popup opens. After selecting either the "Replace" or "Rename" option and clicking "Apply," an "Upload canceled" error message appears.

**To Reproduce**

1. Go to https://core.smartstore.com/backend/admin/category/edit/183/
2. Click the "To upload files drop them here or click" button to upload pictures.
3. Upload the same image with the same name twice. On the second attempt, choose either "Replace" or "Rename." The "Upload canceled" error notification will appear.
4. 
**Expected behavior**
The file should upload correctly without error.

**Screenshots**
![image](https://github.com/user-attachments/assets/63427de1-d464-423b-ae9d-8c2c79872716)

**Additional context**
If I comment out the "dialog.close();" line in the smartstore.dropzoneWrapper.js file, the file uploads correctly, but the "Replace or Skip" popup does not close. It seems that the dialog is closing before the upload request completes, which may be causing the request to be canceled.

**Comment by mgesing** [comment]
I cannot reproduce it anymore with current code, so probably already fixed.

**Comment by amazing12349** [comment]
Thanks for looking into it. I tried the latest code from the main branch on GitHub and I'm still experiencing the issue. Do you have any ideas about what might be causing it on my end?
![image](https://github.com/user-attachments/assets/404a884f-2ede-4fb5-86b8-85428affad94)

**Comment by ngthtung2805** [comment]
@amazing12349  sorry, does it work for you now? I'm having the same issue with the latest code from GitHub. It works in the Media Manager popup but not when I select a file directly, not through the 'Browse Media' button. @mgesing could you please take a look at it again? 

Thanks!

**Comment by mgesing** [comment]
I am still unable to reproduce it.

**Comment by rushikeshkotkar04** [comment]
I'm working on this issue

**Comment by alllucky1996** [comment]
> I'm working on this issue

I have solved it but I'm not sure about the solution or the level of impact so I haven't pushed the code yet. I have passed 'duplicateFileHandling' parameter to the upload-url of file-uploader. The MediaController already has a 'duplicateFileHandling' handler but the client has not used this parameter.

**Comment by rushikeshkotkar04** [comment]
> > I'm working on this issue
> 
> I have solved it but I'm not sure about the solution or the level of impact so I haven't pushed the code yet. I have passed 'duplicateFileHandling' parameter to the upload-url of file-uploader. The MediaController already has a 'duplicateFileHandling' handler but the client has not used this parameter.

I have a logic to do this if need help i can help you
