### ISSUE TITLE
Clear cache not working  

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1188]
hi,

clear cache not working 

![image](https://github.com/user-attachments/assets/ab9f48c5-b4f2-4c27-98b3-a301219bbf00)

**Comment by ngthtung2805** [comment]
Hey @muratcakir ,  just curious why you updated it to '_stringEntries'. From the .NET runtime, I believe it's still '_entries' (https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs). After changing it to '_stringEntries', it no longer works on our Smartstore version deployed on the alpine. I changed it back to '_entries' and it works, so I just wanted to mention it here.

Thanks!
