### ISSUE TITLE
HtmlWidgetTagHelper & WidgetTagHelper NullReferenceException

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1194]
Hi,

I am getting the following error.

NullReferenceException: Object reference not set to an instance of an object.
AspNetCoreGeneratedDocument.Views_PageObjectItem.<ExecuteAsync>b__24_68()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(bool useCachedResult, HtmlEncoder encoder)
Smartstore.Web.TagHelpers.Shared.HtmlWidgetTagHelper.GetContentAsync(TagHelperContext context, TagHelperOutput output) in WidgetTagHelper.cs
-
            if (output.Content.IsModified)
            {
                output.CopyTo(content);
            }
            else
            {
                var childContent = await output.GetChildContentAsync();
                output.Content.SetHtmlContent(childContent);
                output.CopyTo(content);
            }
            
            return content;
        }
Smartstore.Web.TagHelpers.Shared.WidgetTagHelper.ProcessCoreAsync(TagHelperContext context, TagHelperOutput output) in WidgetTagHelper.cs
-
                output.SuppressOutput();
                return;
            }
            var content = await GetContentAsync(context, output);
            output.SuppressOutput();
            if (content != null && !content.IsEmptyOrWhiteSpace)
            {
                var widget = new HtmlWidget(content) { Order = Ordinal, Prepend = Prepend, Key = Key };
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)

**Comment by Michael-Herzog** [comment]
Hi,
where did you get this error?

**Comment by suatsuphi** [comment]
I'll take one on the razor page.
 

```
@if (Model.Id > 0)
{

}
```


because the model is null


` @if (Model != null && Model.Id > 0)`

**Comment by Michael-Herzog** [comment]
Where are you??? Which view/razor page?

**Comment by suatsuphi** [comment]
If any razor page model of my own application is null and I put an if block, I get this error.

**Comment by suatsuphi** [comment]
the model comes null in the view and the model is in the if control on the page. ctrl + F5 to debug the page. 
I get this error  

```
@model PageObjectItemModel

@if(Model.Id > 0)
{
    <div> 
          ...
    </div>

}
```

**Comment by suatsuphi** [comment]
I gave you the wrong information.  It is related to the model being null, but in use in the script...

```
<script sm-target-zone="scripts" data-origin="createorupdate-pageobject-item">
var selectedPageTypeValue = '@Model.PageObject.Type';
var selectedPageGenreValue = '@Model.PageObject.Genre';
.... 
</script>
```

@Model.PageObject?.Type  and @Model.PageObject?.Genre  It is solved by controlling null values. (with ?)
