### ISSUE TITLE
Checkout going straight to final step

### ISSUE THREAD

**Issue by bandieramonte** [smartstore/Smartstore#1206]
**Describe the bug**
Checking out after having checked out recently would take user straight to the confirmation step. 

**To Reproduce**
1. Add a product to cart.
2. Go to checkout and complete all steps, effectively buying the product.
3. Continue shoping, add another product to cart, and go to checkout again.
4. This time checkout would be in the last step (confirmation) instead of in the initial step. 

**Expected behavior**
Checkout should again be in the initial step. User might need to change delivery address, shipping or payment methods. 
If this was done purposefully for convenience, this might surprise or confuse users.

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser: chrome 130.0.6723.70 (Official Build) (64-bit)

**Comment by mgesing** [comment]
Quick-Checkout is one of the major features of next version 5.2. If you prefer the former step-by-step checkout, deactivate Quick-Checkout in the checkout tab in shopping cart settings.

**Comment by bandieramonte** [comment]
I just tested as you suggested, and not it works as expected. I did not know this was a configurable setting within the dashboard. 
Thank you for clarifying.
Closing this as not a bug.
