### ISSUE TITLE
Smartstore.EmailReminder - translation errors

### ISSUE THREAD

**Issue by schraufi** [smartstore/Smartstore#1207]
It took me many hours, but I found a mistake in the German translation that leads to a wrong setting!

At "Bedingungsdatum" these two settings were swapped.
Bestellung versendet <---> Bestellung abgeschlossen

![Screenshot 2024-11-01 230424](https://github.com/user-attachments/assets/c438c77a-d8ae-4702-a649-98b78d5472fa)

have nice evening

**Comment by etinosaizekor** [comment]
Hello. I'm interested in fixing this bug

**Comment by markwoerdenweber** [comment]
Already fixed for [5.1.0](https://github.com/smartstore/enterprise-modules/commit/5570f3195d7c49506d1b3316b38800e0667b71a0) and [main](https://github.com/smartstore/enterprise-modules/commit/affaebeb77455a43197e85a29da73232d51f7922).

**Comment by schraufi** [comment]
I have now set the following setting and the email is still not being sent 😬

The setting EmailReminderSettings.ReviewCondition has been changed. The new value is OrderCompletedDate.

The email should be sent after 7 days, but nothing happens ...
