### ISSUE TITLE
after the update to 6.0 -> Incorrect syntax near '$'.

### ISSUE THREAD

**Issue by schraufi** [smartstore/Smartstore#1224]
I get the following error when I update from 5.1.0 to 6.0.
It is a win x64 system.
![Screenshot 2024-12-11 193700](https://github.com/user-attachments/assets/2dd29b56-6a3f-4fb4-b062-765965641217)

Failed executing DbCommand ("4"ms) [Parameters=["@__systemName_0='?' (Size = 400), @__entityName_1='?' (Size = 400), @__customerRoleIds_2='?' (Size = 4000), @__entityName_3='?' (Size = 400), @__customerRoleIds_4='?' (Size = 4000)"], CommandType='Text', CommandTimeout='30']"
""SELECT [m0].[Id], [m0].[BeginGroup], [m0].[CssClass], [m0].[DisplayOrder], [m0].[HtmlId], [m0].[Icon], [m0].[IconColor], [m0].[LimitedToStores], [m0].[MenuId], [m0].[Model], [m0].[NewWindow], [m0].[NoFollow], [m0].[ParentItemId], [m0].[PermissionNames], [m0].[ProviderName], [m0].[Published], [m0].[ShortDescription], [m0].[ShowExpanded], [m0].[Style], [m0].[SubjectToAcl], [m0].[Title], [m1].[Id], [m1].[DisplayOrder], [m1].[IsSystemMenu], [m1].[LimitedToStores], [m1].[Published], [m1].[SubjectToAcl], [m1].[SystemName], [m1].[Template], [m1].[Title], [m1].[WidgetZone]
FROM [MenuRecord] AS [m]
INNER JOIN [MenuItemRecord] AS [m0] ON [m].[Id] = [m0].[MenuId]
INNER JOIN [MenuRecord] AS [m1] ON [m0].[MenuId] = [m1].[Id]
WHERE [m].[SystemName] = @__systemName_0 AND [m].[Published] = CAST(1 AS bit) AND ([m].[SubjectToAcl] = CAST(0 AS bit) OR [m].[Id] IN (
    SELECT [a].[EntityId]
    FROM [AclRecord] AS [a]
    WHERE [a].[EntityName] = @__entityName_1 AND [a].[CustomerRoleId] IN (
        SELECT [c].[value]
        FROM OPENJSON(@__customerRoleIds_2) WITH ([value] int '$') AS [c]
    )
)) AND [m0].[Published] = CAST(1 AS bit) AND ([m0].[SubjectToAcl] = CAST(0 AS bit) OR [m0].[Id] IN (
    SELECT [a0].[EntityId]
    FROM [AclRecord] AS [a0]
    WHERE [a0].[EntityName] = @__entityName_3 AND [a0].[CustomerRoleId] IN (
        SELECT [c0].[value]
        FROM OPENJSON(@__customerRoleIds_4) WITH ([value] int '$') AS [c0]
    )
))
ORDER BY [m0].[ParentItemId], [m0].[DisplayOrder]"

What could be the reason for this?

**Comment by mgesing** [comment]
The compatibility level of the SQL Server database must be set to "SQL Server 2016" or higher. This can be done with MS SQL Server Management Studio in the database properties (tab "Options") for instance.
