### ISSUE TITLE
Can we store images in amazon s3 or another file storage option

### ISSUE THREAD

**Issue by chillpilllike** [smartstore/Smartstore#1228]
Hello team

does smart store allows us to store images in amazon s3 or any other data storage platform?

Thank you!

**Comment by muratcakir** [comment]
Yes, in Azure BLOBs storage with the commercial module _Smartstore.Azure_.

**Comment by chillpilllike** [comment]
How to purchase it, have sent numerous email to know the price and procedure to purchase but no one replies.

**Comment by stefanmuellerdo** [comment]
@chillpilllike Sorry, we did not receive a mail from "chillpillike" recently. Please send it again via our web based contact form: https://smartstore.com/en/contact-us-2/ 
Thank you.
