### ISSUE TITLE
Conditional attributes - where?

### ISSUE THREAD

**Issue by jakubsenk** [smartstore/Smartstore#1232]
Hello, one of the main features of Smartstore 6 were conditional attributes. I wanted to try it localy before updating in production. However, it seems it's missing or I just don't know how to configure it. I found this article on this topic here https://smartstore.com/en/plug-in-set-visibility-of-individual-product-attributes-with-rules/ but I don't see these options. After a while I noticed that it is meant to be only some kind of plugin and not the feature of smartstore itself. I couldn't find where to get/buy this plugin as it's not within the smartstore solution. How can I enable it for the shop?

Merry Christmas to you all :)

**Comment by mgesing** [comment]
Yes, it is a commercial plugin. You can contact Smartstore about this. You can find the contact details at the end of the article you linked.

**Comment by jakubsenk** [comment]
I see. I thought it was contact for questions and not for actual purchase. I'll write there then.
