### ISSUE TITLE
Possibility to upload an image of a manufacturer via the WebApi or Import Profiles.

### ISSUE THREAD

**Issue by TripleNico** [smartstore/Smartstore#296]
At this time the only option via de WebApi is to upload a product image and via the Import Profiles function only Product and category images. Please add the possibility to the extend this with manufacturer image? For our use it would be most usefull if this can be added to the WebApi. If this is to difficult then add it to Import Profiles.

**Comment by mgesing** [comment]
Possible via API v.5: image upload via POST /MediaFiles/SaveFile and manufacturer assignment via PATCH /Manufacturers({id}).
