### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by EvK** [smartstore/Smartstore#350]
It seems that PostgreSQL is not supported yet, but after little investigation it's quite possible that it will not require too many efforts. With minor modifications I was able to install SmartStore on fresh PostgreSQL instance and perform basic operations (make orders, do some administration etc). Didn't find anything that does not work so far, but didn't try too hard also. 

Given that full version of SQL Server costs quite some money and free edition has limitations which might be considered serious in many cases (limited cpu cores, consumed RAM, database size) - adding support for free database without limitations might seriously increase the usefullness of the product. 

Even more, SQL Server (including SqlCE) requires Windows machine, while PostgreSQL might run on linux one, which is a huge plus by itself, but also might allow to run whole product on Mono, because Entity Framework, ASP.NET MVC are already available under Mono. This possibility to be able to run whole product on a linux server is quite promising, and dependency on SQL Server products is the most serious obstacle.

**Comment by volanar** [comment]
Are there any plans to support postgresql?

**Comment by muratcakir** [comment]
We'll start with `SqlServer` and `MySql`. `PostgreSQL` _may_ follow later.

**Comment by mubarack** [comment]
Hi All, i get error installing smartstore integration with postgres, is there specific DB, db user and password to connect to the database? let me know thanks in advance

**Comment by mgesing** [comment]
There are no special credentials for the server or the database. Use the credentials specified during PostgreSQL installation. By default these are: Server name **localhost**, Username **postgres**.
