### ISSUE TITLE
Optimize/Simplify Checkout Process

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#353]
- Show rich popup after product was added to cart (instead of the simple notification)
- Simplify address entry
- Enable skipping of shipping address entry
- B2B: companies should be able to place orders without providing a first and last name

**Comment by stefanmuellerdo** [comment]
I found this issue from 2015 and would like to add (after internal and external discussions) that I received lately a number of feedback points regarding **checkout**. It might be valuable to go through our checkout **experience** to see where we stand. Often talked is about Click Reduction: Some users feel there are too many **clicks** required to finalize an order. Streamlining this is possible? Then there have been reports of login issues, with some even experiencing double logins to external integrations. Thanks!
