### ISSUE TITLE
DependingPrices: Column CustomerNumber not showing

### ISSUE THREAD

**Issue by TripleNico** [smartstore/Smartstore#391]
Since 4.1.1 the column CustomerNumber isn't visible at a product:
![image](https://user-images.githubusercontent.com/64465421/109790725-fe706880-7c11-11eb-9231-f2496326999f.png)

**Comment by Michael-Herzog** [comment]
The problem was fixed and the plugin was updated in the marketplace.
http://community.smartstore.com/index.php?/files/file/153-depending-prices/

**Comment by TripleNico** [comment]
Thanks, just tested and the issue is indeed fixed.

Ps. The releasenotes don't match the fix?
![image](https://user-images.githubusercontent.com/64465421/110316998-cf8c3500-800b-11eb-9ff2-cc946abda195.png)
