### ISSUE TITLE
Page Builder: new option for Blocks to change content on different device sizes 

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#399]
In Page Builder there should be a new option for Blocks.
If the device size changes, the content should change, too.

Sometimes some content makes sense only on mobile devices. 

A **workaround** is to change **visibility** and than use multiple Blocks with different content for each device size (see gif how to change visibility for device sizes)
![34FA99D0-E2F1-44BD-B7F1-133E9CEC33C9](https://user-images.githubusercontent.com/54363171/111458354-9e051f00-8719-11eb-9e38-09ef99c9f282.GIF)

This has been reported by a shop owner for advertising technology.

**Comment by muratcakir** [comment]
That would result in a complete architectural rewrite. We better leave that as it is for now.

**Comment by wsmig** [comment]
super pleased with how quickly this issue was addressed. Lots of thanks!
