### ISSUE TITLE
Add previewimage link of NewsItem to RSS feed

### ISSUE THREAD

**Issue by TripleNico** [smartstore/Smartstore#403]
Is it possible to add the link to the preview image of a news item to the RSS feed?

**Comment by mgesing** [comment]
Yes, that's possible through SyndicationLink.CreateMediaEnclosureLink.

**Comment by TripleNico** [comment]
Ah thanks! Just to confirm this can't be done currently via the UI?

**Comment by mgesing** [comment]
No, only by code.

**Comment by TripleNico** [comment]
Alright, thanks for your explanation!
