### ISSUE TITLE
Libsass Error. OS:Linux

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#426]
/*
Unable to load shared library 'libsass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsass: cannot open shared object file: No such file or directory
*/

**Comment by muratcakir** [comment]
We haven't included `libsass` for Linux yet, only for Windows. But feel free to deploy on your own.

**Comment by ericsofts** [comment]
I'm try many times ago.. but always show me wrong as below...
/*
Unable to load shared library 'libsass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsass: cannot open shared object file: No such file or directory
*/

Do you have any idea?
