### ISSUE TITLE
Web API: add filter attribute to support IEEE754Compatible header to serialize 64bit number values as strings

### ISSUE THREAD

**Issue by mgesing** [smartstore/Smartstore#429]
See [this post](https://stackoverflow.com/a/58844768).

**Comment by dspaeth-easybill** [comment]
Two examples when it is an issue, to use json numbers:

```javascript
let json = '{"a":17.954, "b": 0.001, "c": 17.955}';
let  obj = JSON.parse(json);

console.log(obj.c.toFixed(2))
// "17.95"
// vs
console.log((obj2.a + obj2.b).toFixed(2))
// "17.96"
```

```java
class Application {
  public static void main( String[] args ) {
      System.out.println(1000000.0f + 1.2f - 1000000.0f);
  }
}

// 1.1875
```

**Comment by dspaeth-easybill** [comment]
The question is, has this to be considered as a bug? For a single order / invoice every thing is fine, as long as I use the pre calculated values, but issues arises when I start to make my own calculations for data warehouse purposes over multiple orders.

**Comment by mgesing** [comment]
Resolved in Smartstore Classic 4.x.
