### ISSUE TITLE
Installation Error!

### ISSUE THREAD

**Issue by mchinchilla** [smartstore/Smartstore#436]
The following images shows the error .. (SQL Server)

![image](https://user-images.githubusercontent.com/5103578/132933270-9de62b53-e1b3-4ede-9498-f712184d9abb.png)

![image](https://user-images.githubusercontent.com/5103578/132933297-8f3401c5-1061-46aa-a405-5afd4ad7dab4.png)

Best regards.

MCh.

**Comment by ericsofts** [comment]
Yes. Options didn's copy.

**Comment by mgesing** [comment]
Should work now.
