### ISSUE TITLE
LoginModel's DisplayExternalAuth = (await _signInManager.GetExternalAuthenticationSchemesAsync()).Any();

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#444]
'model.DisplayExternalAuth' threw an exception of type 'System.NullReferenceException'

I think, maybe the SmartSignInManager is not final?

Or direct use the model.DisplayExternalAuth=_externalAuthenticationSettings.ActiveAuthenticationMethodSystemNames.Any()???

**Comment by Michael-Herzog** [comment]
I've spent a lot of time on this page (testing all kinds of stuff and implementing) and never could raise this exception.
