### ISSUE TITLE
As for the Filter of ExternalAuthFilter, it seems that it is not effective in real time?

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#445]
As for the Filter of ExternalAuthFilter, it seems that it is not effective in real time?

When I set ExternalAuth enabled in the background, the front-end ExternalAuthFilter does not display the externalauth I have enabled? Is it a problem?

Only when I restart the Application will it take effect.

**Comment by Michael-Herzog** [comment]
This also isn't reproducable. A filter will be excuted with every request. Just add a breakpoint and see for yourself.
