### ISSUE TITLE
DefaultTypeConverter cannot convert settings enum data to enum

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#446]
File:DefaultTypeConverter.cs
Bug:Every Setting's Enum Data cannt converter to Enum.
Code:
        public virtual object ConvertFrom(CultureInfo culture, object value)
        {
            // Use Convert.ChangeType if both types are IConvertible
            if (!_typeIsEnum && _typeIsConvertible && value is IConvertible)
            {
                return Convert.ChangeType(value, _type, culture);
            }

            // Use Enum.ToObject if type is Enum and value is numeric 
            if (_typeIsEnum && value is IConvertible)
            {
                return Enum.ToObject(_type, value);
            }

            if (SystemConverter != null)
            {
                return SystemConverter.ConvertFrom(null, culture, value);
            }

            throw Error.InvalidCast(value.GetType(), _type);
        }

**Comment by muratcakir** [comment]
It would be very helpful if you could post the target enumeration type and the source value (and concrete type) by debugging.
