### ISSUE TITLE
Preview Campaign

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#449]
1. Create queued email from template, the Render templates of RenderEmailAddressAsync(messageTemplate.To, messageContext);
messageTemplate.To has data of {NewsletterSubscription.Email}, Result is NULL.

2. Double click "/admin/messagetemplate/preview/1?isCampaign=true" show Error as below:

InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList<IUpdateEntry> entriesToSave, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Smartstore.Data.DbSaveChangesOperation.ExecuteAsync(bool acceptAllChangesOnSuccess, CancellationToken cancelToken) in DbSaveChangesOperation.cs
-
            Exception exception = null;
            await using (await DoExecuteAsync())
            {
                try
                {
                    return await _ctx.SaveChangesCoreAsync(acceptAllChangesOnSuccess, cancelToken);
                }
                catch (Exception ex)
                {
                    exception = ex;
                    throw;
                }
Smartstore.Data.DbSaveChangesOperation.ExecuteAsync(bool acceptAllChangesOnSuccess, CancellationToken cancelToken) in DbSaveChangesOperation.cs
-
                {
                    return await _ctx.SaveChangesCoreAsync(acceptAllChangesOnSuccess, cancelToken);
                }
                catch (Exception ex)
                {
                    exception = ex;
                    throw;
                }
            }
            async Task<IAsyncDisposable> DoExecuteAsync()
            {
                var autoDetectChanges = _ctx.ChangeTracker.AutoDetectChangesEnabled;
Smartstore.Data.HookingDbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken) in HookingDbContext.cs
-
            }
            _currentSaveOperation = new DbSaveChangesOperation(this, this.DbHookHandler);
            try
            {
                return await _currentSaveOperation.ExecuteAsync(acceptAllChangesOnSuccess, cancellationToken);
            }
            finally
            {
                _currentSaveOperation?.Dispose();
                _currentSaveOperation = null;
            }
Smartstore.Core.Data.SaveChangesAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in SaveChangesAttribute.cs
-
                    return;
                }
                var db = context.HttpContext.RequestServices.GetRequiredService(DbContextType) as DbContext;
                if (db != null)
                {
                    await db.SaveChangesAsync();
                }
            }
        }
    }
}

**Comment by Michael-Herzog** [comment]
Resolved via https://github.com/smartstore/Smartstore/commit/c44f97b663a509b46ce2e98109adb1f327560d20
