### ISSUE TITLE
Bug: Remove 300 sec timeout for large uploads in Media Manager

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#452]
Bug: Remove 300 sec timeout for large uploads in Media Manager

Expected: **large uploads** (like 100 MB video) should be possible on slower internet connections, and **not auto-canceled** after 300 seconds, with a *then* very fast vanishing *"request timeout error 300 seconds"* message. So user has really no idea why upload was not possible.

**Comment by muratcakir** [comment]
Not relevant for Smartstore Core.
