### ISSUE TITLE
DbQuerySettings invalid.

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#455]
One store in database:
IgnoreAcl: False
IgnoreMultiStore: False

Two stores in database:
IgnoreAcl: False
IgnoreMultiStore: False

**Comment by muratcakir** [comment]
Do you have any ACL or StoreMapping records in your database. Because these are checked too.

**Comment by ericsofts** [comment]
Yes. just tested.

One store/Empty ACL or StoreMapping records in database:
IgnoreAcl: False
IgnoreMultiStore: False

Two stores/Multi records ACL or StoreMapping in database:
IgnoreAcl: False
IgnoreMultiStore: False
