### ISSUE TITLE
CheckBoxHiddenInputRenderMode.Inline is mistake?

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#466]
In AddViewOptions
o.HtmlHelperOptions.CheckBoxHiddenInputRenderMode = CheckBoxHiddenInputRenderMode.Inline;

there will be two checkbox post. because it will set a same name input control to View.
One is Checkbox
Two is hidden Input.

Change to:
o.HtmlHelperOptions.CheckBoxHiddenInputRenderMode = CheckBoxHiddenInputRenderMode.None;
This way will fixed. show only checkbox control view.

**Comment by muratcakir** [comment]
It is `Inline` on purpose to restore legacy MVC behavior. `None` is wrong: it would not send values for unchecked checkboxes.
