### ISSUE TITLE
Check NuGet online feed always timeout.

### ISSUE THREAD

**Issue by ericsofts** [smartstore/Smartstore#468]
Check NuGet online feed & download package always timeout.
I thinks  this way not friendly.. local NuGet package is best way for use.

**Comment by muratcakir** [comment]
Yes, but before using a package locally it needs to be downloaded first. Could you please give more input about what happens? When? Which OS? Firewall active?... I need more info about the environment.

**Comment by ericsofts** [comment]
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.DirectoryInfo.Create()
   at Smartstore.Engine.Modularity.NuGet.NuGetExplorer.GetOfflinePackageFolder() in E:\Projects\Smartstore\src\Smartstore\Engine\Modularity\NuGet\NuGetExplorer.cs:line 70

**Comment by muratcakir** [comment]
Has been [fixed](https://github.com/smartstore/Smartstore/commit/2aebbe74ae922968c0d3ee6e4b01fa8a78e60230) on 05 Jan already. If directory creation fails due to insufficient access rights for IIS_IUSRS, then app will fallback to `App_Data/.nuget/packages`.
