### ISSUE TITLE
Resources must not contain \r\n 

### ISSUE THREAD

**Issue by Michael-Herzog** [smartstore/Smartstore#494]
Some translators have entered linebreaks  (\r\n) while creating resources. 
These linebreaks lead to broken js code, when used there. 
(I've already corrected some of these resources where I found them e.g. for the french language pack which I have downloaded in my test store)

To fix this issue once and for all we must update the translate app. 

1. Do not permit entering of  \r\n anyhow
2. Write task to get rid of all existing linebreaks (\r\n)

**Comment by mgesing** [comment]
We have already discussed this in the past. Line breaks and other non-displayable characters are quite a regular part of string resources. See for example Admin.Configuration.Category.Acl.AssignToSubCategoriesAndProducts.Hint or Plugins.Payments.Sofortueberweisung.PaymentNote. If specific code (e.g. JavaScript) has problems with this, then it is responsible for this itself and may have to remove these characters.

On the other hand, I am not aware of any case where line breaks need to be at the beginning or end of a string resource. These cases can indeed be removed by Translate.

Translate has no infrastructure for tasks. That would also be the wrong way here. Instead, there is a clean-up function that corrects faulty HTML tags, for example.

**Comment by muratcakir** [comment]
Trimming any leading or trailing whitespace on save or cleanup would be sufficient IMHO.

**Comment by mgesing** [comment]
Resolved. Not yet deployed (comes later when everything is finished).
