### ISSUE TITLE
Discounted prices: comply to legal regulations when displaying discounts

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#497]
See https://www.haendlerbund.de/de/ratgeber/marketing/3826-preiswerbung for more information

**Comment by stefanmuellerdo** [comment]
also here

Neue Preisangabenverordnung ab 28. Mai 2022

Neue Regelungen bei Preissenkungen
So ist bei jeder Bekanntgabe einer Preisermäßigung der vorherige Preis anzugeben, den der Händler vor der Preisermäßigung über einen bestimmten Zeitraum angewendet hat. 
Der vorherige Preis ist der niedrigste Preis, 
den der Händler 
innerhalb eines Zeitraums von mindestens 30 Tage 
vor der Anwendung der Preisermäßigung 
angewendet hat 
(§ 11 PAngV neue Fassung).

https://www.ihk.de/osnabrueck/recht-und-fair-play/handel-und-gewerbe/gewerberecht/pangvo-ab-mai-2022-5384446
