### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by haidoor** [smartstore/Smartstore#524]
Hello team,

Downloaded the latest build and I'm getting the following error on installation:

An unhandled exception occurred while processing the request.
SmartException: No constructor for InstallPermissionsInitializer was found that had all the dependencies satisfied.
Smartstore.IServiceProviderExtensions.ResolveUnregistered(IComponentContext scope, Type type) in IServiceProviderExtensions.cs, line 58

Here is the full stack:
SmartException: No constructor for InstallPermissionsInitializer was found that had all the dependencies satisfied.
Smartstore.IServiceProviderExtensions.ResolveUnregistered(IComponentContext scope, Type type) in IServiceProviderExtensions.cs
+
            throw new SmartException("No constructor for {0} was found that had all the dependencies satisfied.".FormatInvariant(type?.Name.NaIfEmpty()));
Smartstore.Engine.Initialization.ApplicationInitializerMiddleware+<>c__DisplayClass13_0.<InitializeAsync>b__0(InitModuleInfo x) in ApplicationInitializerMiddleware.cs
+
                .Select(x => new InitModule
System.Linq.Enumerable+SelectListIterator<TSource, TResult>.ToArray()
System.Linq.Buffer<TElement>..ctor(IEnumerable<TElement> source)
System.Linq.OrderedEnumerable<TElement>.ToArray()
System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source)
Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.InitializeAsync(HttpContext context) in ApplicationInitializerMiddleware.cs
+
            var modules = pendingModules
Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in ApplicationInitializerMiddleware.cs
+
                            await InitializeAsync(context);
Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in BundleMiddleware.cs
+
                await _next(httpContext);
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Thank you

Haider

**Comment by muratcakir** [comment]
Fixed by a23de8d
