### ISSUE TITLE
Theme FlexBlack: use local version of Abel font

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#537]

**Comment by MarkusH-Berlin** [comment]
Unfortunately the in the blog offered solution to embed Abels fonts locally does not work. Is there anything else to do, to make it work?

https://smartstore.com/de/tipps-tricks-dynamisch-eingebettete-google-fonts-entfernen-oder-lokal-bereitstellen-2

**Comment by Michael-Herzog** [comment]
Why doesn't it work? Do you have a URL where I can take a look?

**Comment by MarkusH-Berlin** [comment]
I sent you an PM / email with the URL.

Please check the following screenshots.
Both files (Abel-Regular.ttf & _fonts.scss) has been copied into the folder /Themes/FlexBlack/Content.
The Caches has been deleted, the shop restarted.
The Abel files are still loaded from the Google servers.

<img width="615" alt="Bildschirmfoto 2022-09-06 um 17 46 58" src="https://user-images.githubusercontent.com/112764786/188687116-e99a4a42-8a18-4239-bf12-322ae27e977e.png">
<img width="882" alt="Bildschirmfoto 2022-09-06 um 17 51 33" src="https://user-images.githubusercontent.com/112764786/188687219-7013b9fe-8675-4b24-86a7-72033f90ebf9.png">
<img width="1496" alt="Bildschirmfoto 2022-09-06 um 17 52 24" src="https://user-images.githubusercontent.com/112764786/188687361-7df20d36-4e0c-4bdb-a390-d62e04a1e1b8.png">

**Comment by Michael-Herzog** [comment]
You must also edit the theme.config. Have you done this?

**Comment by MarkusH-Berlin** [comment]
No, that was my question; anything else to do to make it work?

To modify the theme.config was not part of the instruction, posted under (has been deleted now):
https://smartstore.com/de/tipps-tricks-dynamisch-eingebettete-google-fonts-entfernen-oder-lokal-bereitstellen-2

The instruction was, to download the google font Abel, and copy it, together with the _fonts.scss to /themes/flexblack/content; as I did.

Then open _fonts.scss with an editor and follow the instructions.
But this file did not include any instructions, just anything about Arabic and Chinese language for multilingual shops.


--------------------------------


// ---------------------------------------------------------------------------------------------------------------------
// If your shop is multilingual, you can define font families on language level in this file.
// You have to upload the font files to your webserver yourself, unless you include a web font, e.g. from Google.
// 
// The examples below are for clarification only, customize or add any section you wish.
// ----------------------------------------------------------------------------------------------------------------------


// Arabic
// --------------------------------------------------
/*
html[lang="ar"] {
	@font-face {
		font-family: 'Cairo';
		src:url('https://fonts.googleapis.com/css?family=Cairo');
	}
	body {
		font-family: 'Cairo', sans-serif;
	}
}
*/

// Chinese
// --------------------------------------------------
/*
html[lang="cn"] {
	body {
		font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;
	}
}
*/

// Persian 
// --------------------------------------------------
/*
html[lang="fa"] {
	@font-face {
		font-family: 'Iranian Sans';
		src:url('../../../Content/Fonts/irsans.ttf');
		src:url('../../../Content/Fonts/irsansb.ttf');
	}
	body {
		font-family: 'Iranian Sans';
	}
}
*/

**Comment by MarkusH-Berlin** [comment]
What to edit in theme.config ?

----------------------------------

<?xml version="1.0" encoding="utf-8" ?>
<Theme baseTheme="Flex" title="Flex Black" previewText="'Flex Black' default theme" author="SmartStore AG" version="1.0">

  <Vars>
    <Var name="indigo" type="Color">#3f51b5</Var>
    <Var name="boxed" type="Boolean">true</Var>
    <Var name="link-color" type="Color">$body-color</Var>
    <Var name="inverse-footer" type="Boolean">true</Var>
    <Var name="footer-bg" type="Color">#464646</Var>
	  <Var name="btn-primary-bg" type="Color">#666666</Var>
	  <Var name="btn-primary-border" type="Color">#444444</Var>
    <Var name="google-font-1" type="String">Abel</Var>
    <Var name="font-family-sans-serif" type="String">Abel, "Helvetica Neue", Arial, sans-serif</Var>
    <Var name="font-size-base" type="String">1rem</Var>
    <Var name="font-size-sm" type="String">0.925rem</Var>
    <Var name="font-size-xs" type="String">0.875rem</Var>
    <Var name="header-bg" type="Color">#111111</Var>
    <Var name="inverse-menubar" type="Boolean">true</Var>
    <Var name="inverse-shopbar" type="Boolean">true</Var>
    <Var name="inverse-navbar" type="Boolean">true</Var>
    <Var name="menubar-bg" type="Color">#111111</Var>
    <Var name="shopbar-bg" type="Color">#444444</Var>
    <Var name="megamenu-bg" type="Color">#666666</Var>
    <Var name="state-info-text" type="Color">#757575</Var>
    <Var name="state-info-bg" type="Color">#e0e0e0</Var>
    <Var name="dropdown-bg" type="Color">#f5f5f5</Var>
    <Var name="dropdown-border-color" type="Color">#9e9e9e</Var>
    <Var name="dropdown-link-color" type="Color">rgba(0,0,0,0.86)</Var>
    <Var name="dropdown-link-hover-color" type="Color">rgba(0,0,0,0.87)</Var>
    <Var name="dropdown-link-hover-bg" type="Color">#eeeeee</Var>
    <Var name="offcanvas-cart-footer" type="Color">#424242</Var>
    <Var name="searchbox-bg-2" type="Color">$light</Var>
    <Var name="search-button-flat" type="Boolean">true</Var>
  </Vars>
</Theme>

**Comment by MarkusH-Berlin** [comment]
I'm sorry, that's not working correctly.

After deleting the line in the theme.config the Abel fonts did not load from local server, but did not load at all.
The Abel font is just missing now.
The fonts in the frontend of the shop changed and became fat (ugly), looks like the missing (Abel) font that has been replaced.

That's no solution; it's not working.
I switched back to the unmodified theme.config.

Please check attached screenshot, Abel fonts is missing at all after modifying theme.config.

<img width="226" alt="Bildschirmfoto 2022-09-06 um 20 35 21" src="https://user-images.githubusercontent.com/112764786/188713696-c24f96ee-0da6-4b54-9adc-3b4bc8db30d8.png">

**Comment by MarkusH-Berlin** [comment]
That's a screenshot of the modified theme.config.
Did I delete the correct line (I think so); just for the case...

<img width="848" alt="Bildschirmfoto 2022-09-06 um 20 45 09" src="https://user-images.githubusercontent.com/112764786/188714625-fc7afc6e-8642-4a35-aed8-01154ebd027a.png">

**Comment by Michael-Herzog** [comment]
Hi,
you must also add css declarations to include the font on your server. Just google for _include font css_
Regards,
Michael

**Comment by MarkusH-Berlin** [comment]
I'm sorry, but Smartstore already posted an instruction how to embed the Google Abel Fonts locally, to make Smartstore (with Theme Black Flex) legal again according to DSGVO.

https://smartstore.com/de/tipps-tricks-dynamisch-eingebettete-google-fonts-entfernen-oder-lokal-bereitstellen-2

This post / instruction was obviously not working correctly or not complete, and has been deleted meanwhile from the Smartstore Server.

I received this incomplete not working instruction also by email directly from Smartstore.

I followed the instructions, and it did unfortunately not work.

I posted several screenshots (check above) to make clear it's not working.

Then you told me I also would have to delete a certain line in the _fonts.scss file.

I have done this as well, and it's unfortunately still no working; again.

I posted screenshots again, and now you want me to add "css declarations".

Please let me know what exactly I have to add where exactly, the info just google "include font css" does not help at all.
What exactly is to include where exactly...?

Can you / Smartstore not just provide a complete and working solution to embed the Abel fonts locally (like in the deleted Blog post, just a complete and working instruction).

Please just provide a complete and working theme.config file (I'm just a user and not a software developer, I don't know where and how to add css declarations if you don't write me exactly what to do and where to do).

Or even better, provide a complete and working instruction or security patch for everybody (every Smartstore 4 installation with Theme FlexBlack) is not running legally according to DVSGO, because of this unsolved issue.

Please provide a working solution to fix this issue asap.

Thank you very much in advance!

Best Regards
Markus

**Comment by Michael-Herzog** [comment]
Please look at my last commit or contact our support team for help.

**Comment by MarkusH-Berlin** [comment]
I asked already the support, they sent my the not working instruction by email; same like the deleted Blog post.

https://smartstore.com/de/tipps-tricks-dynamisch-eingebettete-google-fonts-entfernen-oder-lokal-bereitstellen-2


This was the email I received yesterday from your support:

Anleitung Google Font wegmachen
 
Hallo Herr XXXXX, wir werden dazu einen Blogbeitrag noch veröffentlichen, hier schon mal das wesentliche vorab, vielleicht hilft das.
 
 
Ab Version 5.0.1
Der Font Abel wird im FlexBlack Theme lokal eingebunden und nicht mehr über die Google-Cloud bezogen werden. Damit ist das GDPR-Problem obsolet.
Im Theme-Konfigurator blenden wir über dem Google-Webfonts Konfigurator eine Warnung ein.
 
Jetzt:
Problem betrifft nur FlexBlack.
Option 1: Kunde wechselt Theme.
Option 2: Kunde wechselt Font (Abel à Segoe UI). Siehe unten.
Option 3: Kunde bindet Abel lokal ein.
 
Anleitung Option 2:
/Themes/FlexBlack/theme.config mit einem beliebigen Texteditor öffnen.
<Var name="google-font-1" type="String">Abel</Var> entfernen.
<Var name="font-family-sans-serif" type="String">Abel, "Helvetica Neue", Arial, sans-serif</Var> entfernen.
Das war’s!!!!!!!!!!!!!!!!!
 
Anleitung Option 3:
Fonts (alle Schnitte, 100, 300, 500, 700 etc.) runterladen und in Ordner /Themes/FlexBlack/Content packen (bzw. /Themes/FlexBlack/wwwroot in Smartstore 5)
Datei /Themes/Flex/Content/_fonts.scss kopieren nach /Themes/FlexBlack/Content
Datei öffnen und Anleitung befolgen
Das war’s!!!!!!!!!!!!!!!!!
 
 
Freundliche Grüße,
 
XXXXX
Kundenberatung
