### ISSUE TITLE
Theme configuration: display a GDPR warning above Google Webfonts configurator

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#538]

**Comment by MarkusH-Berlin** [comment]
Unfortunalely no working solution so far.

Since Smartstore deleted the Blog post...

https://smartstore.com/de/tipps-tricks-dynamisch-eingebettete-google-fonts-entfernen-oder-lokal-bereitstellen-2

will there be a new (working) instruction to solve that issue?

Please keep in mind every Smartstore.NET 4 installation (with Theme FlexBlack) is not running legally anymore, according to DVSGO.

**Comment by Michael-Herzog** [comment]
There are working solutions! There are a lot of people who reached out to us, contacted our support team and got the help they needed. 
Regards

**Comment by MarkusH-Berlin** [comment]
This was the email I received yesterday from the Smartstore support.
I sent an answer but never received any reply.

Why Smartstore does not just post an official solution, that anybody can use?
Like the meanwhile deleted Blog Post above.

I don't understand Smartstore makes such a secret and creates so much work and trouble for everyone involved.

Please just post an official and working way in your Forum or Blog to solve that legal issue that every Smartstore.NET 4 user is concerned about. Where is the problem...?!


This was the email I received yesterday from the Smartstore support.
--------------------------------------------------------------------------------------------
Anleitung Google Font wegmachen

Hallo Herr XXXXX, wir werden dazu einen Blogbeitrag noch veröffentlichen, hier schon mal das wesentliche vorab, vielleicht hilft das.

Ab Version 5.0.1
Der Font Abel wird im FlexBlack Theme lokal eingebunden und nicht mehr über die Google-Cloud bezogen werden. Damit ist das GDPR-Problem obsolet.
Im Theme-Konfigurator blenden wir über dem Google-Webfonts Konfigurator eine Warnung ein.

Jetzt:
Problem betrifft nur FlexBlack.
Option 1: Kunde wechselt Theme.
Option 2: Kunde wechselt Font (Abel à Segoe UI). Siehe unten.
Option 3: Kunde bindet Abel lokal ein.

Anleitung Option 2:
/Themes/FlexBlack/theme.config mit einem beliebigen Texteditor öffnen.
Abel entfernen.
Abel, "Helvetica Neue", Arial, sans-serif entfernen.
Das war’s!!!!!!!!!!!!!!!!!

Anleitung Option 3:
Fonts (alle Schnitte, 100, 300, 500, 700 etc.) runterladen und in Ordner /Themes/FlexBlack/Content packen (bzw. /Themes/FlexBlack/wwwroot in Smartstore 5)
Datei /Themes/Flex/Content/_fonts.scss kopieren nach /Themes/FlexBlack/Content
Datei öffnen und Anleitung befolgen
Das war’s!!!!!!!!!!!!!!!!!

Freundliche Grüße,

XXXXX
Kundenberatung
