### ISSUE TITLE
Smartstore.Packager

### ISSUE THREAD

**Issue by meysam999** [smartstore/Smartstore#545]
![image](https://user-images.githubusercontent.com/113003869/190097372-a837ea0c-fa1a-4ab2-a8dc-21407ce860ea.png)

**Comment by mgesing** [comment]
I don't get an error message when compiling Smartstore.Tools (including the packager). Have you pulled the current code from GitHub, including that of the dependent projects Smartstore and Smartstore.Core?

**Comment by meysam999** [comment]
yes. I got it from GitHub last week.

![image](https://user-images.githubusercontent.com/113003869/190108132-0182d3f5-9156-4a63-90b8-6e9bcaf77e93.png)


I did not find the required extension

**Comment by meysam999** [comment]
I updated to the latest version and the problem was solved
