### ISSUE TITLE
Product attribute stock is ignored when adding to cart

### ISSUE THREAD

**Issue by Macka323** [smartstore/Smartstore#555]
**Describe the bug**
When a product has attributes (variants) you can purchase more than there is in stock

**To Reproduce**
Steps to reproduce the behaviour:
#
1.1. Create a product with variant
1.2. set inventory tracking to be to inventory tracking by product attributes
or
1.1. Use the iPad from the sample products 
1.2. set inventory tracking to be to inventory tracking by product attributes 
 ##
3.change how much a variant is in stock
4.then when you go to the product page and you can purchase that variant more than it has in stock
#

**Expected behaviour**
To show a warning that you cannot purchase from that variant than how much is in stock

**Screenshots**

**Desktop (please complete the following information):**
commit # 874afa64668a54aa6c32388063e09d6c15a8081b
Windows 11

**Additional context**
![image](https://user-images.githubusercontent.com/75259519/198410775-ec9d8b4d-1d72-433f-9676-450f3001c1e8.png)
![image](https://user-images.githubusercontent.com/75259519/198411003-4d65770b-5b6d-4b82-bce7-f5264d08b0d1.png)
![image](https://user-images.githubusercontent.com/75259519/198411055-c278ca35-cdf1-449c-a04b-ad8215a99571.png)
![image](https://user-images.githubusercontent.com/75259519/198411082-ea033cc2-4113-4bea-8e21-51a60a7b8f49.png)

**Comment by Michael-Herzog** [comment]
Hi,
Be shure that the **Manage inventory method** of your product is set to **Track inventory by product attributes** 
and that the property **Allow out of stock** of your combination is set to false.
Regards
