### ISSUE TITLE
Howto: add a custom SearchFilterDescription (SmartStore 5)

### ISSUE THREAD

**Issue by CribAd** [smartstore/Smartstore#561]
I want to add an new rule for dynamic selection of products on a category page, based on an attribute that is not yet available as product rule. 

I found the List<SearchFilterDescription> in  ProductRuleProvider.cs (SmartStore.Core), but what is the prefered way to add a new SearchFilterDescription, to be sure the rule stays there when we update the source?

**Comment by mgesing** [comment]
I would try a CustomProductRuleProvider that inherits from ProductRuleProvider, overrides LoadDescriptorsAsync on its own, calls base.LoadDescriptorsAsync and adds my custom descriptor(s) to the returned list.

**Comment by CribAd** [comment]
Ok, sounds great, but I don't know how to do this.

Where do I need to place my code? Is there any documentation available that describes how to do create overrides?

**Comment by mgesing** [comment]
Just [register](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Core/Catalog/Bootstrapping/CatalogStarter.cs#L43) it using Autofac.
