### ISSUE TITLE
Plugin: ZIP instead of NUPKG

### ISSUE THREAD

**Issue by Belott** [smartstore/Smartstore#568]
The plugins in the marketplace are NUPKG-Files. I try to upload such a NUPKG plugin, but smartstore expect a ZIP-file. It's not possible to install a NUPKG plugin.

Windows 10
Microsoft Edge
Smartstore Version 5.0.1.0

**Comment by Michael-Herzog** [comment]
Smartstore plugins were already updated. Which plugin are you trying to install?

**Comment by Belott** [comment]
I try to install the plugin "Remove billing address": http://community.smartstore.com/index.php?/files/file/149-remove-billing-address-in-checkout/

**Comment by Michael-Herzog** [comment]
Please contact the author and ask him if and when he will update the plugin.

**Comment by Belott** [comment]
The documentation tells me, that a plugin must be a NUPKG file. So, is the documentation wrong?
Check: https://smartstore.atlassian.net/wiki/spaces/SDDE50/pages/1956127470/Plugins+oder+Themes+installieren
