### ISSUE TITLE
Roules don't affect shipping method

### ISSUE THREAD

**Issue by Belott** [smartstore/Smartstore#569]
I activated a requirement on a shipping method. When I save the shipping configuration, the roule counter in the list of the shipping methods doesn't count up. 

1. Konfiguration/Regionale Einstellungen/Versandarten
2. Click on a shipping method
3. Add a requirement to the shipping method
4. Click on "save"
5. In the overview of the shipping methods, the "Number of rules" column is still set to zero. If you check the previously stored requirement for the shipping method, you will find that the requirement was actually added. However, if you actually test the requirement/rule, you will notice that the rule is not applied.

I would expect that the "Number of Rules" column correctly counts the stored rules and that the rule is actually applied.

![image](https://user-images.githubusercontent.com/113674761/205671949-0cdc7bd0-a2b1-4d1a-9e02-0307f633ebf8.png)
![image](https://user-images.githubusercontent.com/113674761/205671988-32d97cce-1c46-435b-9e2a-523e658947b0.png)

Windows 10
Microsoft Edge
Smartstore V. 5.0.1

**Comment by mgesing** [comment]
Thank you for reporting. This has since been fixed by 13e72ae6105b473306127cab5fe7bcac6a49eb78.
