### ISSUE TITLE
Bug related to the payment method

### ISSUE THREAD

**Issue by bangvl** [smartstore/Smartstore#576]
After publish, when the installation was done. I couldn't see the list of Payment Methods
Link: /admin/payment/providers/

Could you explain this issue ? And how to display the Payment Method ? 

Related to the Payment Methods, if the Payment Method list is null then Customer could not use checkout page.

Many thanks.

**Comment by mgesing** [comment]
Probably the Modules folder is missing in your deployment including the modules with the payment methods.

**Comment by bangvl** [comment]
> Probably the Modules folder is missing in your deployment including the modules with the payment methods.

I don't think so, when I published the SmartStore.Web project I didn't see the Modules folder in published folder.

I already copied the Modules folder in SmartStore.Web\Modules to my published folder and install again, but it's not working.

**Comment by bangvl** [comment]
When i built the SmartStore.Stripe, the error message: 

Unhandled exception. System.Text.Json.JsonException: '/' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 6 | BytePositionInLine: 2.
7> ---> System.Text.Json.JsonReaderException: '/' is an invalid start of a property name. Expected a '"'. LineNumber: 6 | BytePositionInLine: 2.
7>   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
7>   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
7>   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
7>   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
7>   at System.Text.Json.Utf8JsonReader.Read()
7>   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
7>   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
7>   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
7>   --- End of inner exception stack trace ---
7>   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
7>   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
7>   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
7>   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
7>   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
7>   at Smartstore.ModuleBuilder.Program.ReadModuleDescriptor(String manifestFilePath)
7>   at Smartstore.ModuleBuilder.Program.DeployModule(DirectoryInfo moduleDir)
7>   at Smartstore.ModuleBuilder.Program.DeployModules(String[] modulePaths)
7>   at Smartstore.ModuleBuilder.Program.Main(String[] args)
7>F:\Working\SmartStoreBase\src\Smartstore.Build\Smartstore.ModuleBuilder\Smartstore.BuildModule.proj(15,5): error MSB3073: The command "dotnet "Smartstore.ModuleBuilder.dll" "ModulePath=F:\SmartStore\src\Smartstore.Modules\Smartstore.Stripe\..\..\Smartstore.Web\Modules\Smartstore.Stripe\"" exited with code -532462766.
