### ISSUE TITLE
Currency manager backend: enhance confusing UI

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#580]
- Separate _Live currency rates_ from list
- Remove the _Get live rates_ button in header
- Save all rates in cache once fetched (don't fetch live on every load)
- Reload rates only if refresh is performed explicitly

**Comment by mgesing** [comment]
> Separate Live currency rates from list

What exactly is meant by this? Why to separate? Should the live currency rates be moved to somewhere else? Doesn't make sense to me to separate anything here.

I would combine everything into one currency grid with two columns _applied rate_ and _live rate_. The _get live rates_ button will be moved from the header to the grid toolbar, renamed _Update live rates_. And I would leave the options tab as it is and add caching as described above.
