### ISSUE TITLE
Forums: Duplicate views when a topic is visited

### ISSUE THREAD

**Issue by pecoranet** [smartstore/Smartstore#586]
When a topic is visited and go back to forums, the "VIEWS" shows the value as if counts twice.

I think the problem is the double redirection to Topic Action in BoardsController.
![Sin título](https://user-images.githubusercontent.com/103253329/209220468-778920ea-7d02-44da-9785-92e7e939d27e.png)

**Comment by mgesing** [comment]
I can't reproduce this in either 4.2 or 5.0.1. What do you mean by "double redirection"?

**Comment by pecoranet** [comment]
Steps to reproduce the problem:
1) I had installed a clean 4.2.0 version (from release zip file in github
2) Login with admin account and go to Forum (upper menu)
3) Click in any forum (I navegate to "New Products", created by default.
4) Click on button "New Topic" and create a topic (title/priority normal/check Published, uncheck "notify me via email when someone posts in this topic) and click on submit.
5) The new topic is on the screen sucessfully. Click in breadcrumb on "News Products" (the parent forum).
6) The new topic appears with 2 views! 




![Sin título](https://user-images.githubusercontent.com/103253329/236921329-f28c20c3-f1bb-451d-aafc-e41b68d25deb.png)

7) If you go again to "sss" (new topic) and go back, 4 views is shown, and 6 views, and go on... (2 times each visit)

The execution passes twice on this action:

![imagen](https://user-images.githubusercontent.com/103253329/236922338-188812f6-2f36-41fe-a1b8-4133a915c6bd.png)

**Comment by mgesing** [comment]
I cannot reproduce it with either 4.2 or the current version 5.0.4. Debugging does not show the described behavior either. The action method is executed once, not twice.
