### ISSUE TITLE
Delete Import Profile from Profile list

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#598]
**Is your feature request related to a problem? Please describe.**
Yes when trying to edit some of the older profiles  i created.I get error 

 ArgumentNullException: Value cannot be null. (Parameter 'source')

The excel import file was not  correct 

**Describe the solution you'd like**
To be able to delete the profile from the List of Profiles 

**Describe alternatives you've considered**

**Additional context**

**Comment by mgesing** [comment]
I cannot reproduce that. A full stacktrace of the exception would be helpfull.

**Comment by mrrcomp** [comment]
Hi

This is the full error screen

ArgumentNullException: Value cannot be null. (Parameter 'source')
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
·       Stack
·       Query
·       Cookies
·       Headers
·       Routing
·                     ArgumentNullException: Value cannot be null. (Parameter 'source')
o    System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
o    System.Linq.Enumerable.Any<TSource>(IEnumerable<TSource> source)
o    AspNetCoreGeneratedDocument.Areas_Admin_Views_Import__ColumnMappings.ExecuteAsync() in _ColumnMappings.cshtml
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
o    Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, object model, IView view)
o    Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
o    AspNetCoreGeneratedDocument.Areas_Admin_Views_Import__Update.ExecuteAsync() in _Update.cshtml
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
o    Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, object model, IView view)
o    Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
o    AspNetCoreGeneratedDocument.Areas_Admin_Views_Import_Edit.<ExecuteAsync>b__18_0() in Edit.cshtml
o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(bool useCachedResult, HtmlEncoder encoder)
o    Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
o    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
o    AspNetCoreGeneratedDocument.Areas_Admin_Views_Import_Edit.ExecuteAsync() in Edit.cshtml
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
o    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
o    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
o    Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
o    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
o    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
o    Smartstore.Core.Localization.RequestCultureMiddleware.Invoke(HttpContext context, IWorkContext workContext) in RequestCultureMiddleware.cs
o    Smartstore.Core.Bootstrapping.CheckoutBootstrappingExtensions+<>c+<<UseCheckoutState>b__0_0>d.MoveNext() in CheckoutBootstrappingExtensions.cs
o    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
o    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
o    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
o    Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
o    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
o    Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in ApplicationInitializerMiddleware.cs
o    Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in BundleMiddleware.cs
o    Smartstore.Core.Content.Media.MediaLegacyMiddleware.Invoke(HttpContext context, Lazy<IMediaService> mediaService, Lazy<IMediaUrlGenerator> mediaUrlGenerator) in MediaLegacyMiddleware.cs
o    Smartstore.Core.Content.Media.MediaMiddleware.Invoke(HttpContext context, MediaSettings mediaSettings, Lazy<IMediaService> mediaService, Lazy<IFolderService> folderService, Lazy<IPermissionService> permissionService, Lazy<IWorkContext> workContext, Lazy<MediaHelper> mediaHelper, Lazy<IEnumerable<IMediaHandler>> mediaHandlers, ILogger<MediaMiddleware> logger) in MediaMiddleware.cs
o    StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
o    Smartstore.Core.Logging.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext, IWebHelper webHelper, IWorkContext workContext) in RequestLoggingMiddleware.cs
o    Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
o    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Regards

Meir

**Comment by mgesing** [comment]
I still cannot reproduce it. Please re-open if it still exists, preferably with an import file that generates the error "The excel import file was not correct" mentioned.
