### ISSUE TITLE
Goggle Analytics

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#600]
**Describe the bug**
I enter the google id and do a save it says "saved" but the id reverts to UA-0000000-0
I also tried to enter the "manual tag" from the Google website also after save it reverts back to the original

**Comment by Michael-Herzog** [comment]
Hi,
I can't reproduce this problem. Are you using the latest code?
Regards,
Michael

**Comment by mrrcomp** [comment]
Hi
I am using 5.0.0

Regards

Meir

**Comment by Michael-Herzog** [comment]
Please update to the latest code.

**Comment by mrrcomp** [comment]
Last time i tried to update after doing the copy of the files it still registered 5.0.0 :)

Couldn't figure out why 

which folders must i delete before uploading via ftp?

Regards
Meir

**Comment by Michael-Herzog** [comment]
Hi,
I also faced an issue like that on time. Most probably the files just weren't overwritten. Make shure to stop the app pool of your IIS application before uploading.
Regards,
Michael
