### ISSUE TITLE
Delete corrupt input profile

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#601]
**Describe the bug**
REopening the issue that give error when attempting to re-open previous profile if base xls has error.
**To Reproduce**
1. Create New Import Profile
2. import attached file
3. Save Profile Definition.'
4. Tryh to re-open profile
[pricelist3_1 (1).xlsx](https://github.com/smartstore/Smartstore/files/10426294/pricelist3_1.1.xlsx)

**Expected behavior**
Reopen the profile so it can reload a proper file or be able to delete the profile from the list of profiles !

**Comment by mgesing** [comment]
The error has been fixed by 20852eae8ed12d64cebce952b70de74a60c6c085. You are probably working with an old version.
