### ISSUE TITLE
Docker HTTP ERROR 500 after installation

### ISSUE THREAD

**Issue by nicoleonwien** [smartstore/Smartstore#606]
**Describe the bug**
I wanted to implement Smartstore with Docker as described in this tutorial. This also worked well in the installation process but as soon as I got the message that the Smartstore was installed successfully, and I am not automatically redirected the page does not load, and I get an HTTP ERROR 500. Tried it also with different Database servers, but nothing works. Also with Nginx Proxy Manager and Plain Smartstore with direct Port 80 access.

https://smartstore.atlassian.net/wiki/spaces/SMNET50/pages/1956119258/Running+Smartstore+and+Database+together+as+Docker+Containers

**To Reproduce**
1. Create a Docker Compose file like in the documentation, and it will give you the error.

**Expected behavior**
I would like to see the normal Smartstore Landing Page after installation but that not happened, and I also not got any error.

**Desktop (please complete the following information):**
 - OS: Debian 11 with Docker
 - Browser: Brave and Edge

**Comment by bastonta** [comment]
this bug occurs due to incorrect UAParser settings, in the UAParserUserAgent class on line [124 FromYaml](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Core/Platform/Web/UAParserUserAgent.cs#L124) expects yaml content but not the file path
