### ISSUE TITLE
Build DeleteGuestCustomers query with LINQ again 

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#608]
The raw SQL query won't work with PostgreSql. Unification across 3 providers seems hard. However, because we can bulk delete now there is no need for raw SQL anymore.

The LINQ query should conceptually operate like the current SQL query:
- First delete generic attribute records
- Then delete customer records
- The LIMIT for every bulk delete call is 20.000

Also: publish an event message right before the query is executed to give external modules the chance to alter the query. For example, the Forum module must also join `PrivateMessage`, `ForumPost` and `ForumTopic`.

**Comment by muratcakir** [comment]
Test against MySQL, PostgreSQL and SQLite after merge.

**Comment by mgesing** [comment]
Successfully tested with SQL-Server, MySQL, SQLite and PostgreSQL.
