### ISSUE TITLE
Error on remove product from shopping cart

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#609]
**Describe the bug**
Have 1 item in my shopping cart try to delete get error 

Object reference not set to an instance of an object.  
or
An error occured duriing the removal of the product
add product to shoppping cart 
goto basket try to hit the delete (garbage can)
 

This is happening on both my stores 

I did a application restart still same issue

website is https;//robinscreations.store

meir
![product_delete](https://user-images.githubusercontent.com/710257/213977315-526ca07f-1d17-4971-a57c-07bbbbc62e1b.png)

**Comment by mgesing** [comment]
Fixed by 8462f684ed112058987d8148869a254236502c67.

**Comment by mrrcomp** [comment]
sorry how do i get that fix onmy site?//

meir
