### ISSUE TITLE
PayPal Error ( PayPalCheckoutState.PaypalOrderId ) or Error: No ack for postMessage createOrder() in https://www.paypal.com in 10000ms

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#611]
*When trying to place an order and pressing the confirm button at the https://store.mrrcomputers.cc/checkout/confirm/ webpage I get the error below:
Missing checkout session state (PayPalCheckoutState.PayPalOrderId). Your payment cannot be processed. Please go to your shopping cart and checkout again.
To Reproduce

Add some products
Select paypal method
Go to checkout at /checkout/confirm/
Scroll down to Confirm and press the button
See error "Falta el estado de la sesión de pago ( PayPalCheckoutState.PaypalOrderId ). Lo sentimos, su pago no puede ser procesado. Por favor, vuelva a la cesta de la compra y pase de nuevo por la caja."
Expected behavior
A new window where I can submit my data to use paypal

Additional context

I'm running SmartStore 5.0.2
Using the plugin Paypal 5.0.2

**Expected behavior**
being able to continue payment

**Comment by mrrcomp** [comment]
HI

This error occurs if its the first order in the system. I created an order using other payment method and then second order was able to connect to PayPal to complete but instead i get error 

Error: No ack for postMessage createOrder() in https://www.paypal.com in 10000ms

 Thanks

**Comment by Michael-Herzog** [comment]
This is probably due to the missing checkout state. We've already fixed this with the branch 5.0.2.x

**Comment by mrrcomp** [comment]
how do i load that version?

I have 5.0.2

meir

**Comment by Michael-Herzog** [comment]
Either you compile the source of 5.0.2.x or you just wait a few days for the next release or if you have booked support with us you can just contact our support team to obtain the hotfixes.
