### ISSUE TITLE
Smartstore emails are sent with the email priority low

### ISSUE THREAD

**Issue by manu-1012** [smartstore/Smartstore#612]
Every email that is sent from our Smartstore webserver is sent with the email priority "low". Is it possible to change this setting anywhere or why does this occur? In the attachments you can find screenshots of our email configuration and how the email is shown in Outlook.

We're running Smartstore version 5.0.1 on the IIS webservice
Windows Server 2022 is running on version 21H2 (Build 20348.1487)

![Email in Outlook](https://user-images.githubusercontent.com/122961841/214221027-1b59de2b-882b-4e77-9e5a-3ddab38c3ce6.png)
![Email configuration](https://user-images.githubusercontent.com/122961841/214221033-23a71d38-aaab-4cd5-bb40-ef200dc3cbcd.png)

**Comment by stefanmuellerdo** [comment]
Hi WAS, thanks for the report. It looks like this will be available soon, at best in the next minor release 5.0.3 next week. Regards Stefan
