### ISSUE TITLE
Shipping Settings

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#613]
**Describe the bug**
Turning off the "Free Shipping Over" does not cancel the option 
**To Reproduce**
1. set free shipping over x to  on
2. set value of to a value
3. free shipping is callculated for product over the value without problem
4. switch off the free shipping the value in the value of remains and during checkout it will take that into account nd not the fact that the free shipping is turned off
5. See error

**Expected behavior**
Not to calcute as free if the free shipping iis off see screen shot )
**Screenshots**
![shippingSettings](https://user-images.githubusercontent.com/710257/214222924-e2d0a4fe-8bd7-4a95-aa92-f5e814c18412.png)

Version 5.0.2

**Comment by mgesing** [comment]
If a multistore setting is deactivated, the value that is set for "All stores" applies to the store. This fallback value is then displayed in a greyed-out colour like in your screenshot.
