### ISSUE TITLE
Error: No ack for postMessage createOrder() in https://www.paypal.com in 10000ms

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#614]
**Describe the bug**
on paypal checkout button of the side basket 
**To Reproduce**
1. add product to basket..'
2. press "paypal chekout" on sidebar window.'

**Expected behavior**

**Screenshots**

![paypal_checout](https://user-images.githubusercontent.com/710257/214360255-94f057cb-9c3c-4cda-ab82-22f54ccb1cc4.png)

**Desktop (please complete the following information):**
 Version 5.0.2 after hotfixes

**Comment by Michael-Herzog** [comment]
I've never encountered this problem and still can't reproduce it. A quick Google serach suggested it might have to do with VS settings. 
https://www.paypal-community.com/t5/PayPal-Payments-Standard/Error-No-ack-for-postMessage-createOrder/td-p/2799595
https://stackoverflow.com/questions/66456892/failed-to-launch-debug-adapter-vs-tries-to-connect-to-a-random-port/66473740#66473740,
