### ISSUE TITLE
Mini Basket layout 

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#615]
**Describe the bug**
When i set paypaly not to display on mini basket i still get on bottom of mini basket the "OR" option

**To Reproduce**
turn off paypal display on minibasket
add product to basket see attached screen shot

**Expected behavior**
to not have the "OR" below the price , go to cart ,and checkout 
![mini-basket](https://user-images.githubusercontent.com/710257/214493424-c33e3ee2-38a8-46ba-baab-239adfa60a06.png)
 
**Desktop (please complete the following information):**
Version 5.0.2 after hotfixes

**Additional context**

**Comment by stefanmuellerdo** [comment]
Hi mrrcomp, thanks for your bug report and screenshots. At the moment I have no information to share with you about the superflous "or" line in the minibasket. But **please stand by for another minor release, 5.0.3,** which I hope will be available next week. As always, it will contain all the hotfixes after 5.0.2.  Regards Stefan.

**Comment by Michael-Herzog** [comment]
Hi,
probably you are testing on localhost and have activated stripe. Stripe renders content in there also but it won't be displayed as long as you're on localhost or haven't set it up correctly. Therefore the or button is still displayed. 
Regards
