### ISSUE TITLE
Tab created with Event.cs does not work on Mobile.

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#622]
**Describe the bug**
`if (tabStripName == "pd-tabs")
            {
                var entityId = ((EntityModelBase)eventMessage.Model).Id;
                var price = ((ProductDetailsModel)eventMessage.Model).Price.FinalPrice;
                await eventMessage.TabFactory.InsertAfterAsync("pd-reviews", builder => builder
                    .Text("Taksit Seçenekleri")
                    .Name("pd-tab-installment")
                    .Icon("fas fa-credit-card", "fas")
                    .LinkHtmlAttributes(new { data_tab_name = "Installment" })
                    .Action("ProductInstallmentTab", "CreditCardWeb", new { productId = entityId, priceAmount = price.Amount })
                    .Ajax());
            }`

Note: This code is taken from the document.
Document Link: https://smartstore.gitbook.io/developer-guide/compose/modules/examples/adding-tabs

With this code, we add a tab to the product detail section. It works fine on desktop but not on mobile. 

**To Reproduce**
1. Enter any product detail page.
2. When you view it from the desktop, the tab will be visible.
3. It works when clicked. (Image This: [https://prnt.sc/CSefyUuR2Ja7](https://prnt.sc/CSefyUuR2Ja7) )
4. When you switch to the mobile version, it does not work when clicking the tab. (`https://prnt.sc/mgKCTmSFruSN`)
5. See error

**Expected behavior**
The tab is expected to work in Desktop and Mobile versions.

**Screenshots**
1. Desktop => https://prnt.sc/CSefyUuR2Ja7
2. Mobile => https://prnt.sc/o4HlHkittFsx
3. Error => https://prnt.sc/mgKCTmSFruSN

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 x64]

**Additional context**
The problem exists in versions 5.2 and 5.3.

**Comment by Michael-Herzog** [comment]
Be sure your returned content looks something like this:

```
<h5 aria-expanded="false" class="nav-toggler collapsed" data-target="#collapse-my-tab" data-toggle="collapse">
Tab title
</h5>

<div class="nav-collapse collapse **show**" id="collapse-my-tab">
Real content
</div>
```
Regards

**Comment by munkerjs** [comment]
As you said, we get returns. But the content is empty.

**Comment by Michael-Herzog** [comment]
Have you pulled the latest code containing my commit?

**Comment by munkerjs** [comment]
When I click it, the content comes up, now the title of the Tab section disappears.

`<h5 aria-expanded="false" class="nav-toggler collapsed" data-target="#collapse-my-tab" data-toggle="collapse">
Tab title
</h5>`

**Comment by Michael-Herzog** [comment]
Add the class show to nav-collapse.

**Comment by munkerjs** [comment]
> Add the class show to nav-collapse.

I don't understand where to install it?

Code Here: https://prnt.sc/vd8_UETukzE1

**Comment by Michael-Herzog** [comment]
Look at the div in the code I've posted above.

**Comment by munkerjs** [comment]
When clicked once on mobile, the content appears, but the tab does not close again.

**Comment by Michael-Herzog** [comment]
Can you please upload this somewhere so I can have a direct look.

**Comment by munkerjs** [comment]
Can you give me your e-mail address? I would like to forward the module file privately to you.

**Comment by Michael-Herzog** [comment]
Send the link to info[at]smartstore.com

**Comment by Michael-Herzog** [comment]
I just checked your plugin. The code I've posted above is completely missing in the view ProductInstallmentTab.cshtml. Just wrap it around thecontent you're returning.
```
<h5 aria-expanded="false" class="nav-toggler collapsed" data-target="#collapse-my-tab" data-toggle="collapse">
Tab title
</h5>

<div class="nav-collapse collapse show" id="collapse-my-tab">
<div class="row mt-2" id="installment-table">
...
</div>
</div>
```

**Comment by munkerjs** [comment]
Thanks, I solved the problem!
