### ISSUE TITLE
Error Occurs While Deleting Product From Offcanvas Shopping Cart and Shopping Cart Page

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#623]
**Describe the bug**

**To Reproduce**
1. Add a product to cart.
2. Go to the cart page, try to delete the product from the cart.
3. You will see the error.
Note: The same error exists in the side-opening shopping cart.

**Expected behavior**
It is expected that the product will be deleted from the cart.

**Screenshots**
1. Shopping Cart Page -> https://prnt.sc/UL7HlimfxIdd
2. Offcanvas Shopping Cart -> https://prnt.sc/yWmsR3FM2YpP
3. Error -> https://prnt.sc/7KlB1lbXW64R

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 x64]

**Additional context**
I discovered this bug in version 5.2. I don't know if there are other versions.

**Comment by Michael-Herzog** [comment]
We've fixPlease pull the latest code.ed this error already. Please pull the latest code.
