### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#634]
Hi

 

I want to do the following and couldn't find a method to allow it...
 

1) non logged in browsers to the site will get "call for price"

2) registered users of type 1 will get tier price a

3) registered users of type 2 will get tier price -b 

 

Is this possible?

 

Regards

 

Meir

**Comment by stefanmuellerdo** [comment]
not really, you can simulate that with customer groups and multiple products for each customer groups, but that does not scale very well and requires heavy configuration (you need to replace on  shop product with three versions, one version is restricted to Guests and has Call for Price activated, one version is restricted to registered Customers an lists tier price a, one version is restricted to registered Customers 2 and lists tier price b). So dont if you have more than 10 products in store.

**Comment by mrrcomp** [comment]
Thanks for the response. Even though you suggest not doing this for more than 10 products since I already have the DB connected to a desktop application that allows me easy access to deal with products and groups a bit easier than using the admin site. So i will consider this solution.

again thanks

meir

**Comment by stefanmuellerdo** [comment]
You may also look  into a commercial plugin called **"Depending Prices".** It enhances the smartstore pricing system, you can set individual prices for individual customers and more.

"This plugin enables you to define deviating prices for different customers (by customer number), customer groups, languages or stores. Deviating prices can be configured to use fixed values, percentage or adjustments. The plugin also allows to define prices for product groups globally. You can asign the price configuration for a product group by simply asigning the product group id to the product."

The plugin can be tested free of charge for 30 days.

http://community.smartstore.com/index.php?/files/file/210-depending-prices/

**Comment by mrrcomp** [comment]
Thanks.. Do you have a price cost for that plugin? or should i send a request via the plugin info link?

**Comment by stefanmuellerdo** [comment]
i send you a mail!

**Comment by stefanmuellerdo** [comment]
this issue can be **closed**

btw. "Depending Prices" plugin is featured in the Smartstore 5.0.4 release notes:  https://github.com/smartstore/Smartstore/releases/tag/5.0.4
