### ISSUE TITLE
debug is not working

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#640]
Hi, 
I download it with "Open with Visual Studio". I click the debug button and waiting for a long time. it is not working ? 

build.cmd >>>>>

PowerShell Desktop version 5.1.22621.963
Microsoft (R) .NET Core SDK version 8.0.100-preview.2.23157.25
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception.
 ---> System.ArgumentException: Could not locate '.nuke' directory/file while walking up from 'C:\Windows\System32'.
Either create a directory/file to mark the root directory, or add '--root [path]' to the invocation.
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Common/Assert.cs:line 61
   at Nuke.Common.NukeBuild.GetRootDirectory() in /_/source/Nuke.Common/NukeBuild.Statics.cs:line 104
   at Nuke.Common.NukeBuild..cctor() in /_/source/Nuke.Common/NukeBuild.Statics.cs:line 23
   --- End of inner exception stack trace ---
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/NukeBuild.cs:line 75
   at Build.Main() in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Build\Smartstore.Build\Build.cs:line 24
Press any key to continue . . .

**Comment by mgesing** [comment]
Did you try **Download ZIP** or to copy the Github URL and clone the repository using a Git client like [Sourcetree](https://www.sourcetreeapp.com/)?

**Comment by suatsuphi** [comment]
same thing. could you try same thing ?


Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 2.0

**Comment by muratcakir** [comment]
Did you also try with a stable (non-preview) Visual Studio release?

**Comment by suatsuphi** [comment]
no, I have a just preview version. I wanna try sqlite with unicode character. There is a patch about it. 

https://github.com/nalgeon/sqlean/blob/main/docs/unicode.md

I am wondering that it is working?

**Comment by muratcakir** [comment]
We enforce case insensitive collation for all string fields by calling `...Properties<string>().UseCollation("NOCASE")` during model bootstrapping. See [SqliteDbFactory.cs#L88](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Data/Smartstore.Data.Sqlite/SqliteDbFactory.cs#L88).

**Comment by suatsuphi** [comment]
also admin panel filter not working. stock filter or category filter all of them

**Comment by Nisaba** [comment]
Hi all,
I've the same issue. I use VS 2022 v. 17.5.3
The solution has been rebuilt with success in Release config.
But when I run the SmartStore.Web project, nothing appears.
Any idea ?
thanks
