### ISSUE TITLE
WebApi SSL requirement optional

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#652]
**Is your feature request related to a problem? Please describe.**
I want to run smartstore behind a nginx proxy (nginx just passes through the data to localhost:5000, but does all the nasty SSL-stuff), since we also want to host a normal webpage on this server.
At the moment the WebApi plugin requires SSL for non-development contexts which makes the deployment of nginx as proxy + smartstore unusable.
It shouldn't be a requirement, even the shop itself can run on http alone.

**Describe the solution you'd like**
Please add a configuration option to disable the SSL requirement.

**Comment by mgesing** [comment]
Closed because the related pull request #653 was closed and noted as no longer required.
