### ISSUE TITLE
Make shoppingcart ajax calls more easily extendable

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#661]
**Is your feature request related to a problem? Please describe.**
At the moment if I want to inject additional data into the return of the UpdateCartItem action it is not possible without rendering the WishilistItems/CartItems views twice (InvokePartialViewAsync calls).
See https://github.com/smartstore/Smartstore/blob/a299af9687df28bec42593d144488cffaa8700d8/src/Smartstore.Web/Controllers/ShoppingCartController.cs#L337-L356

**Describe the solution you'd like**
Some kind of callback to be able to change/adjust the values in the model before InvokePartialViewAsync is called.

**Describe alternatives you've considered**
Only alternative I see is an actionfilter for UpdateCartItem, but then, as I said, the view was already rendered and I have to do it again with my altered values.
Also tried (and failed) to create my own ShoppingCartController, but InvokePartialViewAsync is protected....

**Comment by mgesing** [comment]
Have you tried using an `IResultFilter`?

**Comment by Algorithman** [comment]
Don't think that helps me either, since I need to change the model before it is rendered by InvokePartialViewAsync

**Comment by Algorithman** [comment]
Basically i need to act on line 343 and 349

**Comment by mgesing** [comment]
You're right, that doesn't help in this case. Why do you have to add data to the model here? What should happen with your data?

**Comment by Algorithman** [comment]
We have additional data which the customer can change.
These I need to show (and make them editable which is no problem) in the cart.
It does not really pose a problem for me, I found a way around the protected InvokePartialViewAsync call, but just for performance, rendering views twice is kinda not the thing I want to do :)

For completeness I think every view and it's modeldata should be alterable, you never know what someone needs to do with it.
