### ISSUE TITLE
Using a theme containing any View files causes a crash on load

### ISSUE THREAD

**Issue by nick4501** [smartstore/Smartstore#674]
**Describe the bug**
When attempting to view any front-end page with a custom theme which contains any view files, the page crashes with the following exception message:

**Controller: Error, Action: Error, Status: 500 (InternalServerError)

Cannot find compilation library location for package 'System.Security.Cryptography.Pkcs'**

**To Reproduce**
1. Clone the Flex theme.
2. Copy any view from the main Views folder into the new theme (e.g. /Views/Shared/Components/Footer)
3. Activate the theme from the back-end
4. Visit any front-end page
5. Page crashes with the above exception message

**Expected behavior**
The theme contents are loaded without error

**Screenshots**

**Desktop (please complete the following information):**
**NOT OS/BROWSER-SPECIFIC**

**Additional context**
This was recreated using the latest code in the **main** branch, and is also raised in the forums: http://community.smartstore.com/index.php?/topic/50923-cloning-view-into-new-theme-causes-crash-v504/

**Comment by stefanmuellerdo** [comment]
Thank you for the write-up!

**Comment by Michael-Herzog** [comment]
Hi,
I also have faced this problem, when I was developing on local IIS. My solution was to copy the file System.Security.Cryptography.Pkcs.dll into the root of the app. You can copy it from our release package.
Regards,
Michael

**Comment by nick4501** [comment]
> Hi, I also have faced this problem, when I was developing on local IIS. My solution was to copy the file System.Security.Cryptography.Pkcs.dll into the root of the app. You can copy it from our release package. Regards, Michael

Ah ha! Thanks Michael, that sorted it.  I think this needs to be documented somewhere though - or the build process changed to copy that file to the bin directory.

Thanks again.
