### ISSUE TITLE
gitignore symlinks to module themes

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#705]
**Is your feature request related to a problem? Please describe.**
At the moment git always tells me I have a new folder in Themes (my theme).
Please add something like
```
src/Smartstore.Web/Themes/*
!src/Smartstore.Web/Themes/Flex/
!src/Smartstore.Web/Themes/FlexBlue/
!src/Smartstore.Web/Themes/FlexBlack/
```
This should fix the issue and still keep the original Flex-Themes-Folders in the repo.

**Comment by muratcakir** [comment]
Just a small note: any directory that ends with `-sym` is gitignored by default.

**Comment by Algorithman** [comment]
I've seen the entry, but since smartstore creates the symlink in the themes folder by itself, it should be ignored properly.
Just stumbled over it today since I tried to find a way to keep the repo completely clean (including the solution file) and still have my module in for debugging.
Found a way (thanks `dotnet sln`) but the symlink was left over.
