### ISSUE TITLE
Reverse proxy settings

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#706]
**Describe the bug**
Today I needed to reinstall my local test machine and I deployed a new smartstore instance.

my nginx config is like this:

```
server {
        listen        443 ssl;
        listen          [::]:443 ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;

        server_name   testshop.local;

        root /var/www/proxy;

        location ~ /\.ht {
                deny all;
        }

        location / {
                        proxy_pass         http://127.0.0.1:5000;
                        proxy_http_version 1.1;
                        proxy_set_header   Upgrade $http_upgrade;
                        proxy_set_header   Connection keep-alive;
                        proxy_set_header   Host $host;
                        proxy_cache_bypass $http_upgrade;
                        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header   X-Forwarded-Proto $scheme;
                   }
        }
}
```

If I enable the ReverseProxy/Enabled setting (nothing changed from the original in the repo) I run into a redirect loop.
It's only working if I disable the ForwardForHeader setting.
I don't know if this is caused by my site config or by the middleware, just wanted to let you guys know.

The ForwardProtoHeader works fine though, I can finally access the webapi without jumping through hoops :)

**Comment by zihniartar** [comment]
Hi,

what is meant by redirect loop? 
I just installed Smartstore 5.0.4 on Ubuntu 22 with the same NGINX configuration and ReverseProxy/Enabled and could not detect any redirect loop.

Can you please run the page without SSL and see if the redirect loop is still apparent?

Thanks!

**Comment by Algorithman** [comment]
Sorry, left out my http->https upgrade. Didn't think this would have any impact, but it does.

```
server {
        listen 80;
        listen [::]:80;
        server_name     testshop.local;
        return 307 https://testshop.local$request_uri ;
}
```

It seems the shop is sending back a redirect (301) to http://testshop.local if the ForwardFor setting is enabled which then sends it into a redirect loop.
But the ForwardProtoHeader is active, so why would it send a redirect to http://testshop.local instead of https?

_... after some further investigation ..._

Found the code which does the https downgrade:

https://github.com/smartstore/Smartstore/blob/983d03d71b12169702347dd8f58fb7404cbf5b88/src/Smartstore.Core/Platform/Security/Services/HttpsUrlFilter.cs#L52-L59

This will downgrade your connection (the 301 redirect) if you didn't set ForceSslForAllPages to true in the shop configuration.
Bit counterintuitive to have to set ForceSslForAllPages (since the traffic to the proxy isn't and shouldn't be encrypted), but heck, the whole reverse proxy thing is too.

Something to note for the documentation/FAQ :)

As a side note: It really isn't common anymore to present a http site, SSL is quite cheap nowadays and certainly always recommended to use.

**Comment by Algorithman** [comment]
But i found another thing.
In a reverse proxy setting i needed to add the 
`add_header X-Frame-Options "SAMEORIGIN";`
header, so popups in the admin area weren't blocked.
