### ISSUE TITLE
Add hashing to AttributeSelection

### ISSUE THREAD

**Issue by daniel-streetec** [smartstore/Smartstore#708]
**Is your feature request related to a problem? Please describe.**
When creating Products with multiple attributes, which also have multiple attributes, the amount of ProductVariantAttributeCombination scales quickly. In my case, I have a product with 6 attributes resulting in 560k variations only for this specific product. When selecting a product via ProductAttributeMaterializer -> FindAttributeCombinationAsync it quickly takes a couple of seconds to complete the loop to find the correct combination

```
int index = 0;
await foreach (var combination in combinations)
{
    index++;

    if (selection.Equals(combination.AttributeSelection))
    {
        result = combination;
        break;
    }
}
```

**Describe the solution you'd like**
As mentioned in the comment in the code:

```
// Actually this is an anti-pattern, because we never enumerate the resultset.
// But unless we implement the hashing stuff for attribute combinations this
// is way faster than materializing all combinations just to scan for the selection.
// Anyway, MARS is enabled now, so who cares.
```
it would be a good idea to implement some proper hashing to the AttributeSelection class and propagate that up to ProductVariantAttributeCombination. I've done some steps and added that hash, but I'm not totally aware of all impacts the changes might have on the core. Please check out this [Fork](https://github.com/daniel-streetec/Smartstore/tree/5.0.4.x)

[ProductVariantAttributeCombination](https://github.com/daniel-streetec/Smartstore/blob/5.0.4.x/src/Smartstore.Core/Catalog/Attributes/Domain/ProductVariantAttributeCombination.cs)

[ProductAttributeMaterializer](https://github.com/daniel-streetec/Smartstore/blob/5.0.4.x/src/Smartstore.Core/Catalog/Attributes/Services/ProductAttributeMaterializer.cs)

[AttributeSelection](https://github.com/daniel-streetec/Smartstore/blob/5.0.4.x/src/Smartstore/Domain/AttributeSelection.cs)

[Migration](https://github.com/daniel-streetec/Smartstore/blob/5.0.4.x/src/Smartstore.Core/Migrations/20230515150700_AddAttributeSelectionHash.cs)

**Comment by muratcakir** [comment]
I'm afraid there's a lot more work involved. The biggest challenge is - undoubtedly - migrating old data stock without any _incident_. Because millions of records in the `ProductVariantAttributeCombination` table is not uncommon. Creating a hash for each record and updating all records in a single migration operation can be very time-consuming and error-prone. Thus, we need a very robust migration strategy.

**Comment by daniel-streetec** [comment]
I see your point, but what if you would add a stored procedure for the databases that match the c# function? You could run that sp on every entry in the db on migration... should be pretty fast.
It could be something like that for TSQL
```
CREATE FUNCTION dbo.CalculateHash(@attributesXml NVARCHAR(MAX))
RETURNS INT
AS
BEGIN
    DECLARE @json NVARCHAR(MAX) = (SELECT TOP 1 AttributesXml FROM ProductVariantAttributeCombination WHERE AttributesXml = @attributesXml);
    DECLARE @hash VARBINARY(64) = HASHBYTES('SHA2_256', @json);
    DECLARE @result INT = 0;

    WHILE LEN(@hash) >= 4
    BEGIN
        SET @result ^= CAST(SUBSTRING(@hash, 1, 4) AS INT);
        SET @hash = SUBSTRING(@hash, 5, LEN(@hash));
    END

    RETURN @result;
END
```
