### ISSUE TITLE
Favicon problem fix

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#711]
Hi,

src\Smartstore.Web\Views\Shared\Components\Favicon
Default.cshtml
line 25

`<link rel="shortcut icon" href='@Url.Content($"~/favicon.ico?v={ SmartstoreVersion.CurrentVersion}")' />`

**Comment by muratcakir** [comment]
Please stop talking in **mysteries**! **Describe** the problem first! YOU are the one who has identified a problem, so why not write it down?

In another issue, you came up with a solution to a problem without describing the problem, just the solution... this is a really, really strange form of communication.

**Comment by suatsuphi** [comment]
my English is not very good. I just wanted to show the relevant field. I try to write in detail.

**Comment by muratcakir** [comment]
> my English is not very good. I just wanted to show the relevant field. I try to write in detail.

No problem. Just write in Turkish and let DeepL translate for you. Easy.

**Comment by suatsuphi** [comment]
Sorry. I just realized.
