### ISSUE TITLE
Cart is empty if payment fails for payment type redirect

### ISSUE THREAD

**Issue by samiechan** [smartstore/Smartstore#719]
**Describe the bug**
If payment type is redirect and payment has failed during postProcessPayment method then cart becomes empty. Looking at the code, I can see that PlaceOrderAsync is called on ConfirmOrder in the CheckoutController before postProcessPayment is executed. PlaceOrderAsync empties the cart and returned result is given to the postProcessPayment. The redirection happens after all above steps. Basically, it happens when you use postProcessPayment method for one-off payment plugin which requires OrderGuid for reference and needs to redirect user to the service payment page to complete the payment. However if payment fails, then customer is returned back to the store by callback URL from the payment service. In the result, customer has lost his items from the cart and all the ordering process has been lost as well.

**Expected behavior**
Cart data is restored to the last state if payment has failed.

**Comment by samiechan** [comment]
Moved removal of cart items to Completed method
![image](https://github.com/smartstore/Smartstore/assets/15961166/2736234f-3c14-4662-bf79-2ab706acf7a7)

**Comment by mgesing** [comment]
This view is based on a general misunderstanding of the various payment processes. Payment by redirection is an outdated process intended for older payment services. The buyer has not lost his products or his order process here. The order process has already been completed and the order placed accordingly. The payment is made intentionally only after the order has been placed. In case of an error, the buyer can restart the payment process via his order detail page as often as he likes.

This payment flow is outdated and should no longer be used for new developments. Instead, the payment should be made before the order is received in a way that ensures that the order is accepted. As an example, integrate the payment modules [AmazonPay](https://github.com/smartstore/Smartstore/tree/main/src/Smartstore.Modules/Smartstore.AmazonPay) and [PayPal](https://github.com/smartstore/Smartstore/tree/main/src/Smartstore.Modules/Smartstore.PayPal) integrate their payments into the checkout accordingly.

**Comment by samiechan** [comment]
But what to do if I need orderGuid to initialize one-off payment and then redirect customer to the payment service page? I suppose the initialization can be added to ProcessPaymentAsync in the Payment Provider. But how do I redirect user afterwards to the payment page service URL which is returned after initialization?

**Comment by mgesing** [comment]
> I suppose the initialization can be added to ProcessPaymentAsync in the Payment Provider.

That's too late if you want to redirect before the order is placed.

As I mentioned, you can move the payment flow into the checkout and for instance redirect between payment list page and confirm page. Or like AmazonPay and PayPal modules, you intercept the buy-now button click and redirect there.
