### ISSUE TITLE
Some price label text blocks are not localized

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#725]
**Describe the bug**
Setting Admin.Configuration.PriceLabel.Fields.ShortName.Hint is not localizable.

**To Reproduce**
Go to admin -> settings -> catalog -> prices.
Default "Regular Price" label Dropdown is not localizable.
Same for the Default "Compare Price" label as well.

**Expected behavior**
Frontend text blocks should be localizable.

**Comment by Michael-Herzog** [comment]
The localized values for price labels can be defined here:
Admin / Configuration / Lists / Price Labels 
Once the localized values are added the will be shown also in the settings dropdown.
