### ISSUE TITLE
Delivery time facet options not localized/localizable

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#726]
**Describe the bug**
Frontend delivery time filter facet shows incorrect strings for selected language (other than install language)

**To Reproduce**
- Default shop
- install additional languages
- go to frontend and check delivery time facet on the left

Same goes for QuantityUnit texts.

**Expected behavior**
Filter options should be localized

**Screenshots**
![image](https://github.com/smartstore/Smartstore/assets/2128945/e8ac00c6-95a9-49ef-b9f6-eeb53c020b68)

![image](https://github.com/smartstore/Smartstore/assets/2128945/4766afa1-bcbf-4783-a0b3-d3e7bd18ec52)

**Comment by Algorithman** [comment]
Can be closed too, it is also in Admin->configuration->Lists->Delivery times. My bad

**Comment by Algorithman** [comment]
But it would be nice if they were filled automatically when installing the language.

**Comment by mgesing** [comment]
What should they be automatically filled with? These are properties of entities that the admin has to populate himself. Your screenshot shows sample data of the installation, which are optionally installed for German and English for testing and illustration purposes.

**Comment by mgesing** [comment]
Yes, they are prefilled by installation but installation is possible using DE or EN only. Why would later adding another language change anything at existing delivery times?
