### ISSUE TITLE
Build project in Modules throw error 

### ISSUE THREAD

**Issue by NguyeNgocPhus** [smartstore/Smartstore#730]
**Describe the bug**
HI, In project in modules , I built a project here Smartstore.Twitter.Auth . it threw me this error "Cannot find compilation library location for package 'Microsoft.AspNetCore.Authentication.Twitter'". I didn't edit anything at all.
**To Reproduce**
1. Go to 'Modules/Smartstore.Twitter.Auth'
2. Click on 'Build'
**Screenshots**
![image](https://github.com/smartstore/Smartstore/assets/63158224/8f5e241c-35bf-45c0-857f-4e24d2dc8aa1)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 x64]

**Comment by Michael-Herzog** [comment]
I can't reproduce this. Is the twitter module the only module which throws this error? What about Facebook for instance?

**Comment by NguyeNgocPhus** [comment]
Any module that uses an external library will have the same error. For example, the Smartstore.AmazonPay module that uses the "Amazon.Pay.API.SDK" library has the same error. like Smartstore.Clickatell module without using any external library there is no error
