### ISSUE TITLE
We cannot load Gifs while Media Manager Module is installed.

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#744]
**Describe the bug**
An error occurs while loading Gifs with the Media Manager plugin installed. However, there is no problem when a gif is loaded from CMS -> Media.

An error occurs only when a GIF is dragged from within the module. In addition, when the browse media button is clicked in the module, there are 5 images on the Media side, while there are 8 images when viewed from the CMS -> Media side.

**Expected behavior**
Equal number of images appear in both media views and no problem uploading Gifs.

**Screenshots**
![Screenshot_6](https://github.com/smartstore/Smartstore/assets/32327426/8a0be225-271b-4de1-bab1-d692b1da715c)
![Screenshot_7](https://github.com/smartstore/Smartstore/assets/32327426/9b0ffcc7-7cd0-4d73-8369-988def0dc00b)
![Screenshot_8](https://github.com/smartstore/Smartstore/assets/32327426/d6f6a0f6-f70e-4824-aca4-d3e80f060b50)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 x64]

**Comment by Michael-Herzog** [comment]
Hi,
I can't reproduce this problem. Also I don't understand turkish and thus can't read the error message. Please check your media settings at:
Admin / Settings / Media / Media Types / Image
Regards,
Michael

**Comment by munkerjs** [comment]
Hi Michael,

Error Message: You cannot upload files of this type.

Admin / Settings / Media / Media Types / Image
![image](https://github.com/smartstore/Smartstore/assets/32327426/7621b32c-9f85-4467-866e-44c65be679dc)

**Comment by Michael-Herzog** [comment]
I just testet again and everything works fine here. Are you sure you're trying to upload a file with the extension **.gif**? Can this be another problem with the turkish i ?

**Comment by munkerjs** [comment]
Yes, I load to Gif extension. But might our Media Manager module be outdated? Can you send me the current version?

mail: munker[@]tarkanreklam.com

**Comment by Michael-Herzog** [comment]
I also need the data of the database. Please send a complete zipped backup of the database. Please also transmit the gif files you're trying to upload.

Regards,
Michael

**Comment by munkerjs** [comment]
I sended details at [info@smartstore.com](mailto:info@smartstore.com)

**Comment by Michael-Herzog** [comment]
Hi,
please remove the entry for **Other** from the media settings. It's a duplicate and results in this bug. We will try to solve this bug somehow.
Regards,
Michael
