### ISSUE TITLE
How can I add "/" at the end of all URLs?

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#752]
Hi Smartstore,

We work with SEO agencies that the world considers professional and we need to make a software change. However, we did not know how to make this change fundamentally, and we wanted to ask you.

A SeName is generated when you add a product in the Smartstore.
Link1: https://examplesite.com/red-shoes

**There is no problem in this, but we want to switch to a uniform URL structure. If there is no slah at the end of the url, it should be added automatically and 301 redirected.**

Target: https://examplesite.com/red-shoes/

**How can we do this?**
We have a Url Rewriter module. But here we cannot define all the links individually.

When we add the following code to the Url Rewriter module, we actually reach our goal. But without doing that, how can we basically translate the smartstore's structure into this?

```html
%{REQUEST_FILENAME} !-f
^(.*[^/])$ /$1/ [L,R=301]
``` 

When we add this code, we get errors in all Jquery codes to reach the relevant controller files. So this method doesn't make any sense.

**We are waiting for your help..
Thanks.**

**Comment by muratcakir** [comment]
The easiest solution is to wait for V5.0.5, which should be available in max. 2 weeks. 5.0.5 has a built-in trailing slash feature:

- [TrailingSlashUrlFilter.cs](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Core/Platform/Seo/Services/TrailingSlashUrlFilter.cs)
- [SeoSettings.cs](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Core/Platform/Seo/Configuration/SeoSettings.cs#L124)
