### ISSUE TITLE
Filter Panel on Tables Keeps Open

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#780]
Hello,

The filter panel is open when the page loads. In the previous version (5.0.4) this problem was not present. Should an extra setting be made or is there an error in the JS Codes?

![image](https://github.com/smartstore/Smartstore/assets/32327426/952c8640-3ddc-4c2e-98d4-78b8d6d3b5d2)

**Comment by muratcakir** [comment]
It's a feature ;-) it is open because there are two active filters. If you reset them, it will not expand initially.

**Comment by munkerjs** [comment]
I want it to come off when the first page is loaded without resetting the filter. How can we do this?
