### ISSUE TITLE
Notify success not working in update process in admin quantityunit list

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#785]
Hi,

Notify success not working in update process in admin quantityunit list. Similar situation is valid for all titles in the configuration > list section.

NotifySuccess(T("Admin.Configuration.QuantityUnits.Updated"));

The dropdown menu (edit - delete) does not close when the popup window is completed with the save button.

**Comment by Michael-Herzog** [comment]
Thanks for reporting!
