### ISSUE TITLE
Web project not starting in Visual Studio

### ISSUE THREAD

**Issue by Nisaba** [smartstore/Smartstore#788]
Hi all,
I've the same issue than #640 but I use SQL Server, not SQLLite.
 I use VS 2022 v. 17.5.3
The solution has been rebuilt with success in Release config.
But when I run the SmartStore.Web project, nothing appears.
Any idea ?
thanks

**Comment by pranavpeddi** [comment]
what is the error are you getting?

**Comment by Nisaba** [comment]
OK, it works now.

I found that it doesn't work when IIS Express is selected by defaut in the Start config, even if SmartStore.Web is the main project. I have to select SmartStore.Web once aigain in the Start sub-menu.

![image](https://github.com/smartstore/Smartstore/assets/34550856/ac9c9787-d2d4-49e3-9d3f-d9d2279775d7)
