### ISSUE TITLE
Minor icon issues

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#789]
hi,

there are minor icon issues in admin panel

https://i.ibb.co/YBH5GQb/Untitled.png

and the x in selection__clear is not centered.

```
.select2-container .select2-selection__clear {
    **/* --trailing-action-size: 1.5rem; */**
    display: inline-flex;
    **padding: 6px;
    padding-top: 4px;**
    justify-content: center;
    align-items: center;
    width: var(--trailing-action-size);
    height: var(--trailing-action-size);
    background-color: var(--gray-200);
    color: inherit;
    cursor: pointer;
    font-weight: 600;
    border-radius: 50%;
    border: 0;
    transition: color 0.1s ease-in-out, background-color 0.1s ease-in-out, border-color 0.1s ease-in-out, box-shadow 0.1s ease-in-out;
    position: relative;
    order: 2;
    margin-inline-start: auto;
    font-size: 14px;
    **line-height: 14px;**
}
```

**Comment by muratcakir** [comment]
selection__clear is perfectly centered for me. Screenshot?

**Comment by suatsuphi** [comment]
x doesn't seem to be in the center of the circle. It looks better even if it is 1-2 pixels higher

https://ibb.co/GpkZpM2

**Comment by muratcakir** [comment]
Something is wrong with your CSS. Made any customizations?

**Comment by suatsuphi** [comment]
The problem is that if the font-size is 14px, if it is 12px, it looks centered. 

I tried the following code and it looks better. 

```
.select2-container .select2-selection__clear {
    line-height: 10px;
}
```

**Comment by muratcakir** [comment]
My question was: What else did you change? Because it is perfectly centered for me in all browsers.

**Comment by suatsuphi** [comment]
only the x position seems to be 1 / 2 pixels down. i tried to show it in the picture.

https://ibb.co/0Q1yNdN

**Comment by suatsuphi** [comment]
I solved the problem, when I define it in the font family, the problem is solved. problem because it can't adjust the font size - is it trying to read a font that is not installed? 
font tanımladığımda konu çözülüyor... 
```
.select2-container .select2-selection__clear {
   
    font-family:  'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
}
```
