### ISSUE TITLE
Use different currencies for products?

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#791]
Hi,

In my store, some products are priced in dollars, some in euros and some in Turkish lira. Can development be made to enable the use of different currencies in products?

**Comment by muratcakir** [comment]
Currently: No. A multi-currency enabled pricing matrix for products will be implemented at some point in the future. However, mixed currency display across products is NOT on our TODO list.

**Comment by suatsuphi** [comment]
> A multi-currency enabled pricing matrix for products will be implemented at some point in the future. 
We are looking forward to it. 
In countries where the economy is problematic, unfortunately, prices cannot be quoted in the currency of the country.
thank you...
