### ISSUE TITLE
First click event of checkbox or radio buttons disappear also first opened payment method page type is different

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#795]
Hi,

First click event of checkbox or radio buttons disappear. My opinion the cause of the problem is the following block 

 ```
$(".payment-method-item .form-check-label").on('click', function (e) {
     e.stopPropagation();
     var label = $(this);
     label.removeClass('clicked');
 });
```

also first opened payment method page type is different that I mean page width different. the first time you open it, the page is inside no-gutters. when we open it a second time, it opens as a second line.

https://ibb.co/hWqYCXv

Can you limit the click event to the no-gutters block (top side)? It also appears as mause pointer in the page. 

```
.payment-method-item > .no-gutters {
    &:hover {
        //cursor: pointer;
    }

    &.active {
        background: $gray-100;

        .payment-brand {
            background: #fff;
        }
    }
}
```

```
$(".payment-method-item > .no-gutters").on('click', function (e) {
    var item = $(this).parent();
    var label = item.find("label");

    // Prevent recursive calls.
    if (!label.hasClass('clicked')) {
        label.addClass('clicked');
        label.trigger('click');
    }
});
```

**Comment by suatsuphi** [comment]
tıklama problemini aşağıdaki gibi çözebiliyorum. 

```
        @if (Model.DisplayPaymentMethodIcons)
        {
            <text>
                $(".payment-method-item").on('click', function (e) {
                    var item = $(this);
                    var label = item.find("label");
                    if (e.currentTarget.className.indexOf('active') == -1) {
                        // Prevent recursive calls.
                        if (!label.hasClass('clicked')) {
                            label.addClass('clicked');
                            label.trigger('click');
                        }
                    }
                });

                $(".payment-method-item .radio > .form-check-label").on('click', function (e) {
                    e.stopPropagation();
                    var label = $(this);
                    label.removeClass('clicked');
                });
            </text>    
        }
```

When I switch between two payments, the space is removed as below, and when it first opened that first payment is active, the space on the left side is a problem for small screens (e.g. phone).
https://ibb.co/hWqYCXv

**Comment by suatsuphi** [comment]
> When I switch between two payments, the space is removed as below, and when it first opened that first payment is active,  https://ibb.co/hWqYCXv

there is a gap even if it opens for the second time ->

with a small modification we can fix this problem. 
added this: item.find('.no-gutters > .col')
removed this: opt-info-embedded

```
if (panel.length == 0) {
    panel = $('<div class="opt-info payment-method-info"></div>')
        .appendTo(item.find('.no-gutters > .col'))
        .data('system-name', systemName)
        .data('lazy-info', true);
}
```

**Comment by Michael-Herzog** [comment]
Hi It seems like you're describing two issues in one. The second part I could reproduce and have fixed it. The first part I didn't understand and therefore couldn't reproduce. Please reopen this issue if the problem still exists and explain how to reproduce it.

Regards,
Michael

**Comment by suatsuphi** [comment]
hi,

everything is allright
Thank you

**Comment by suatsuphi** [comment]
a small click problem occurs. for this a small change is required in _checkout.scss 
line 278 > :not(.active)

```
    .payment-method-item {
        &:hover:not(.active) {
            cursor: pointer;
        }
```

**Comment by suatsuphi** [comment]
If this is not added, when any part of the form is clicked, the last checkbox in the form is clicked. 

`if (e.currentTarget.className.indexOf('active') == -1) `

```
if (e.currentTarget.className.indexOf('active') == -1) {
    // Prevent recursive calls.
    if (!label.hasClass('clicked')) {
        label.addClass('clicked');
        label.trigger('click');
    }
}
```

I mean to say

```
@if (Model.DisplayPaymentMethodIcons)
{
    <text>
        $(".payment-method-item").on('click', function (e) {
            var item = $(this);
            var label = item.find("label");
            if (e.currentTarget.className.indexOf('active') == -1) {
                // Prevent recursive calls.
                if (!label.hasClass('clicked')) {
                    label.addClass('clicked');
                    label.trigger('click');
                }
            }
        });

        $(".payment-method-item .form-check-label").on('click', function (e) {
            e.stopPropagation();
            var label = $(this);
            label.removeClass('clicked');
        });
    </text>    
}

```

**Comment by Michael-Herzog** [comment]
Thanks! I've added the missing part.

**Comment by suatsuphi** [comment]
I've tested it now. The klick problem persists.  AUMIEKAU seems to be missing. When an empty part of the form is clicked, the last checkbox is clicked. css is just the visual part... 

click event adds the click property to the whole form. this makes the last checkbox selected when clicking anywhere on the form... if (!$(this).hasClass('active')) control is required.

```
 $(".payment-method-item").on('click', function (e) {
                    if (!$(this).hasClass('active')) {
                        var item = $(this);
                        var label = item.find("label");
                        // Prevent recursive calls.
                        if (!label.hasClass('clicked')) {
                            label.addClass('clicked');
                            label.trigger('click');
                        }
                    }
                });
```

**Comment by Michael-Herzog** [comment]
I think now i got it :-)
