### ISSUE TITLE
Stripe plugin is not working

### ISSUE THREAD

**Issue by AmmadNaseem** [smartstore/Smartstore#796]
**Describe the bug**
When i try to configure stripe plugin then code is broken and giving exception.

**To Reproduce**
1. Go to the admin panel
2. Click on configuration menu and select payment method
3. Scroll down to stripe and click setting icon and configure
4. See error after continue **Smartstore.StripeElements.Controllers.StripeAdminController.Configure(StripeSettings settings) in StripeAdminController.cs, line 37**

**Expected behavior**
I was wanting as the demo of smartstore shown where i can add stripe key for configuration.

**Screenshots**
![devenv_C6gLOaecOj](https://github.com/smartstore/Smartstore/assets/61114465/e73d3f09-40a5-42f6-854e-6a30c3d1128a)

![chrome_AVfQ2qzwXi](https://github.com/smartstore/Smartstore/assets/61114465/34f2f1f4-9faf-455b-b1d8-87252953bb58)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64]
 - Browser: chrome, firefox

**Comment by Michael-Herzog** [comment]
Hi,
I've [just fixed](https://github.com/smartstore/Smartstore/commit/876abc2aa35dc6673a96e05189a4dc3e3cbc980c) this issue.
Regards,
Michael

**Comment by AmmadNaseem** [comment]
Hi,
I want to understand working of this project and plugin development.

Would you like to please give me path?

**Comment by AmmadNaseem** [comment]
Thanks

**Comment by Michael-Herzog** [comment]
Hi,
please write an email to info@smartstore.com. Then I can send you a link to our documentation which is not completed and therefore not published yet. 
Regards,
Michael

**Comment by AmmadNaseem** [comment]
Thank you very much sir!
