### ISSUE TITLE
Defining search words in MegaSearch plugin

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#806]
We purchased the megasearch plugin for a fee. Regarding the subject, we want the plugin to search according to the search word to be defined for the products. Is this possible?

Working logic:

1. By adding a textbox to the product editing area; Words are separated and written with a comma. (same as a product tag but won't create a link)
2. When a search is made on the site; The search word entered in the product will be given priority and the products related to the entered word will be listed.

Result:
1. The word "liquid soap" is not mentioned in any product name on the site.
2. Suppose the word "liquid soap" is added to the product.
3. When you search for liquid soap on the site, the product/products that have this word added to the product came up.

**Comment by mgesing** [comment]
But product tags are meant for exactly what you describe. They have been specially extended with the "Published" property so that a tag is not published and only affects the search index. Why reinvent the wheel now?

**Comment by mgesing** [comment]
From version 5.2.0, the product meta keywords are also included in the search index and there is a new search field boost for this in the MegaSearch configuration.
