### ISSUE TITLE
Doubleclicking login button can lead to 400 BadRequest error page

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#810]
**Describe the bug**
When logging in and doubleclicking the login button it can lead to a 400 (BadRequest) page.

**To Reproduce**
1. Restart server (IMPORTANT)/start smartstore via VS
2. Go to login page
3. Input your login data and doubleclick (important) the login button 
4. Observe the BadRequest error message

Since I only observed this right after a server restart I think it is some caching issue (maybe a weird race condition).

**Expected behavior**
Logging in as usual.

**Desktop (please complete the following information):**
 - OS: linux, on windows I observed this when running a debug session from VS, thought at first it would only occur there
 - Browser all

**Comment by Michael-Herzog** [comment]
Thanks for reporting!
