### ISSUE TITLE
How to block User-Agent in robots.txt?

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#836]
Hello,

We want to block some bots as User-Agent in the robots.txt file. How do we do this?

```
User-Agent: W3C-checklink
Disallow: /

User-Agent: W3C_Validator
Disallow: /

User-Agent: W3C_CSS_Validator
Disallow: /
``` 

These are a few examples. When we write these examples from the management panel, the result is as follows;

![Adsız](https://github.com/smartstore/Smartstore/assets/32327426/d8e8eb69-2df5-436d-93fb-21652b2f4016)

**How can we block this type of User-Agent data?**

**Comment by Michael-Herzog** [comment]
Currently this ain't possible by out of the box settings. We would have to add onther setting for this purpose. Until we have done this you could edit ths RobotsTextFile Action in the CommonController. 
Regards,
Michael

**Comment by muratcakir** [comment]
I [added the setting](https://github.com/smartstore/Smartstore/commit/4d05752e1449fa9bc055f34508f4732bad4715d5) in a quick and dirty way. `ExtraRobotsLines` is a string setting and will be appended to the output as is, without prefixes.

The setting is currently hidden and must be added/edited via **Configuration / Settings / All settings**.

**Comment by Michael-Herzog** [comment]
Replace button _Show items for 'Allow'_ below the textarea with a button group.
