### ISSUE TITLE
Changing the order detail page like cart page 

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#838]
Hi,

Cart page design is very nice... it would be very nice if the order detail page has a similar design.

Also, there is a small css problem in checkout/shippingmethod/. When  --opt-offset is 36px, it appears flush. 

.opt-info,
.opt-info-item {
    --opt-offset: 36px;
}

**Comment by muratcakir** [comment]
This is work in progress... order detail page and all other cart UI instances will adapt to the new design.
