### ISSUE TITLE
Mega Search - Irrelevant Search Hits

### ISSUE THREAD

**Issue by TRKNGRBZ** [smartstore/Smartstore#846]
We have been using Mega Search plugin for 3 months. Our language is Turkish. We are experiencing some problems with the search results. 

Here is an example :

When we try to search "Sırma" word, mega search divides the word sirma into syllables. Mega search first tries to find all "Sırma" results then tries for "Sır" word. You can check through the search link = " https://istekirtasiye.com/search/?q=s%C4%B1rma ".

The product "https://istekirtasiye.com/red-light-sirt-cantasi-kalpli-pembe-baskili-3-bolme-3-lu-set/" is one of the search results. This product has nothing to do with the word "Sırma".

Even though  "Hits contain all searched terms" setting is active this irrelevant searches continue to appear.

**Comment by munkerjs** [comment]
+1

**Comment by mgesing** [comment]
This sounds like unwanted Lucene word stemming results for the Turkish language. Have you tried different text analysis and advanced text analysis in MegaSearch configuration?

**Comment by TRKNGRBZ** [comment]
Thank you for the comment. After we turned off the advanced text analysis the problem seemed to be solved.
