### ISSUE TITLE
EU check VAT service: switch from SOAP to REST API

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#847]
More and more problems with service availability.

- https://ec.europa.eu/taxation_customs/vies/#/technical-information
- https://ec.europa.eu/assets/taxud/vow-information/swagger_publicVAT.yaml

**Comment by Michael-Herzog** [comment]
During my tests the service still was unavailable one time. But I'm not testing on regular basis. So I don't know if there are any improvements. Sorry
