### ISSUE TITLE
CheckoutAttribute MultilineTextbox doesn't accept enter key for a new line in browser

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#856]
**Describe the bug**
The MultilineTextbox Checkoutattribute doesn't allow enter key to be processed. (my guess is the Dropdown.js script prevents it, not verified)

**To Reproduce**
1. Clean install with sample data
2. In admin create a new CheckoutAttribute, type MultilineTextbox
3. Add a product to the cart and switch to the cart page
4. Try to enter multiline text into the textarea element

**Expected behavior**
Multiple lines should be allowed in a textarea form field.

**Desktop (please complete the following information):**
 - OS: Win10 (at least)
 - Browser Chrome (at least)

**Comment by mgesing** [comment]
Thanks for your contribution!

**Comment by Algorithman** [comment]
You're welcome.
One thing, this kind of function is used in other places too, you might wanna check up on these as well.
