### ISSUE TITLE
Update twitter logo for social links

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#860]
Since Twitter is now X the icon should be updated too. 

Fontawesome already updated the font ([see here](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)).
Seems like a quick task, download font and change `fa-twitter` to `fa-x-twitter`.

**Comment by ParthMakode** [comment]
Can you assign me this . I saw that fontawesome is already updated to v6.4 . I will just have to change the labels from fa-twitter to fa-x-twitter

**Comment by Michael-Herzog** [comment]
We must update to 6.4.2 first. Thanks for reporting!
