### ISSUE TITLE
theme-rtl

### ISSUE THREAD

**Issue by moflehsami** [smartstore/Smartstore#867]
**Describe the bug**

when adding rtl language can find any variables such as $gray ..  in the file _variables.scss

/*
Error: Undefined variable: "$gray-100".
        on line 51:37 of ../../../../../admin/_variables.scss
        from line 5:9 of ../../../../../admin/theme-rtl.scss
>> $gray-150:                      mix($gray-100, $gray-200);
   ------------------------------------^

**Comment by Michael-Herzog** [comment]
I can't reproduce this nor can I imagine we had a bug like this in the past. Please give us more information. Which version are you working with? Have you adapted anything? Have you tried to add your own theme?
Regards,
Michael

**Comment by moflehsami** [comment]
<img width="384" alt="image" src="https://github.com/smartstore/Smartstore/assets/73998516/d8c7aaf6-5999-44d0-a25d-1a311da0add2">

I used smartstore version 5.0.5.0 
when I added  language with rtl direction  that's issue happened.

**Comment by Michael-Herzog** [comment]
I can't reproduce this problem in our latest release 5.0.5. Have you downloaded the source code from the release or are you working with one of our branches?

**Comment by moflehsami** [comment]
the [main](https://github.com/smartstore/Smartstore/tree/main) one

**Comment by Michael-Herzog** [comment]
We've changed a lot there regarding theme variables. But currently everything is working as expected. Please make sure you have the latest version and therefore all recent commits.
