### ISSUE TITLE
Admin - Customer - Change password validates all fields but does not save them

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#876]
**Describe the bug**
If you try to change the password of a customer, fields like firstname, lastname etc are validated (blocking password change).
Then if you enter something in it and click on change password button, it changes the password only and disregards the other fields.

**How to reproduce**
- Install smartstore, go into the backend and try to change your password. You shouldn't have any name/DoB/address etc put in yet.
- Try to change the password

Fix: disable the validations for the change password button.
(branch 5.0.5.x)

**Comment by muratcakir** [comment]
The **Change password** input group must be replaced with a button that opens a small modal dialog. The dialog must contain an isolated form that only posts the new password.
