### ISSUE TITLE
Wrong timespan in backend for scheduled tasks

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#879]
**Is your feature request related to a problem? Please describe.**
I have a long running task (can take multiple hours, depending on the number of new products).
What i just noticed: Sometimes it is writing in future tense for a task which was already completed. (see image)
![image](https://github.com/smartstore/Smartstore/assets/2128945/f4e82e31-30a8-43a5-858f-8513b3bf173b)

Checking the times in the database (ScheduleTaskHistory) show the following:
started: 2023-11-07 13:52:49.980947
finished: 2023-11-07 15:07:18.987639
succeeded: 2023-11-07 15:07:18.987639

Time the picture was taken:  16:26 (UTC+1)

Not impacting function, but sure looks weird...

**Comment by muratcakir** [comment]
There seems to be a discrepancy in the server time: UTC+2 vs. UTC+1. Can you please check **Configuration / Settings / General / Default store time zone**.

**Comment by Algorithman** [comment]
You're somewhat correct. My server was on UTC instead of Europe/Berlin. Thought a new server sitting in Berlin would be installed to this timezone automatically by the hoster. My bad.
Thanks for the help tho :)
