### ISSUE TITLE
[5.1.0.x] Theming fix for offcanvas shopping cart

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#885]
**Is your feature request related to a problem? Please describe.**
In the wishlist the buttons for transfer to shoppingcart and delete are aligned on the right, in the shopping cart the respecitve buttons are not.
Seems there is a ml-auto missing in [line 105](https://github.com/smartstore/Smartstore/blob/d5490c233ac73ef44b350b817dc1760cc1cb71c3/src/Smartstore.Web/Views/ShoppingCart/Partials/OffCanvasShoppingCart.cshtml#L105)

**Comment by Michael-Herzog** [comment]
Hi,
I can't reproduce this problem. col-auto is absolutely sufficient for displaying the buttons on the right. 
Regards

**Comment by Algorithman** [comment]
My bad, I don't show the price in the shopping cart for our individual products, if I leave the <div class="col"> in it, it's fine.
