### ISSUE TITLE
Null Reference Exception Error when creating new currency in CurrencyController 

### ISSUE THREAD

**Issue by dstove** [smartstore/Smartstore#890]
Hi, 
Just downladed the latest version off github and built it from scratch, new database etc. 
.net 7, VS2022, Running on MSSQL, local machine.
Once it installed, logged in to admin console and started setting up as follows.
Set county New Zealand to be '1' and set all others to be '100' 
Set English Language Locale to be EN-NZ instead of EN-US.
Clicked on add currency for NZD, and got a debug screen on VS. Stopped server and started again and new currency screen appeared.
Entered currency details and saved details. Got a debug screen again with the same error. Stopped server and started again, no currencies appear and still get debug screen.

Error is as follows.
System.NullReferenceException: 'Object reference not set to an instance of an object.'
 at Smartstore.Admin.Controllers.CurrencyController.<LiveRateList>d__12.MoveNext() in F:\sources\repos\SmartStore5\src\Smartstore.Web\Areas\Admin\Controllers\CurrencyController.cs:line 197

Code that errors is:

          var gridModel = new GridModel<ExchangeRate>
          {
              Rows = rates ?? new(),
              Total = rates.Count
          };

Note: rates variable is null...

probably should be fixed by checking for rates != null...

Dominic.

**Comment by dstove** [comment]
Changed to this, which works...
            var gridModel = new GridModel<ExchangeRate>();

            if (rates != null)
            {
                gridModel.Rows = rates;
                gridModel.Total = rates.Count;
            }

**Comment by Michael-Herzog** [comment]
Hi,
I can't reproduce this error. I've tried in two different installations, one of them was pretty fresh. 
Regards
