### ISSUE TITLE
Add a cart rule for affiliates

### ISSUE THREAD

**Issue by schraufi** [smartstore/Smartstore#896]
I think it's extremely important that you can automatically apply a **rule** to an **affiliate partner**.

For example, it should be possible to apply a discount automatically.
In this way, the partner can offer a purchase incentive for their customers.

**Comment by stefanmuellerdo** [comment]
**Integration of Discount Assignments for Affiliate Links**


**Context:**  
Currently, Smartstore supports affiliate marketing by tracking customers and orders generated through specific URLs provided to marketing partners. However, the system does _not support direct discount assignments_ for purchases made through these affiliate links. This feature was brought up in a forum dialogue http://community.smartstore.com/index.php?/topic/51024-partnerprogramm/ by a user named Alex, who inquired about the possibility of applying a discount (e.g., 10% off) for every purchase made through an affiliate link.

**Feature Description:**  
The proposed feature aims to allow Smartstore administrators to assign percentage discounts directly to specific affiliate links. When a customer makes a purchase through such an affiliate link, they would automatically receive the specified discount at checkout.

**Benefits:**  
1. **Enhanced Marketing Capabilities:** This feature would provide Smartstore users with a powerful tool to incentivize affiliate marketing, encouraging partners to promote their store more effectively.
2. **Improved User Experience:** Customers using affiliate links would benefit from a seamless discount application, enhancing their shopping experience.
3. **Increased Sales:** By offering discounts through affiliate links, stores could potentially see an increase in traffic and sales, benefiting from the marketing efforts of their affiliates.

**Possible Implementation Approach:**  
A potential approach could involve updating the affiliate management system to include an option for specifying discount percentages (or even more promotions attached to the affiliate partner than that) for each affiliate link. The system would then automatically apply this discount to qualifying purchases made through these links. This functionality could be integrated into the existing 'Marketing > Partner Programs' section of Smartstore.

**Alternatives Considered:**  
While custom adaptations via the free Smartstore "Web API" were considered, they might not provide an immediate, correct or user-friendly solution for this specific requirement. Therefore, integrating this feature directly into the standard Smartstore functionality would be the most effective approach.
