### ISSUE TITLE
Allow to control the product availability based on the existence of an attribute combination

### ISSUE THREAD

**Issue by mgesing** [smartstore/Smartstore#909]
A merchant only wants to add certain attribute combinations (not all). The product should only be able to be ordered if an attribute combination exists for the selected attributes. If this attribute combination does not exist, the product should not be able to be ordered. At the moment he has to create all combinations and deactivate those that are not available.

**Comment by muratcakir** [comment]
Sounds reasonable. We gonna need new props on product level though to control the behavior. Details TBD.
