### ISSUE TITLE
paypal checkout issues 

### ISSUE THREAD

**Issue by mrrcomp** [smartstore/Smartstore#916]
**Describe the bug**
When i get to pick payment method  there is no continue button when the default method selected is "Pay Pal" if i then pick other payment method the "next" button appears I can then go back to paypal to continue when i proceed to final stage of paypal (accept terms) and hit the "confirm button" i get the following error message 

The given key 'PayPalOrderId' was not present in the dictionary.

 Windows 10 x6 
chrome, 

Store Version 5.1

My store is store.mrrcomputers.cc

Regards

Meir

**Comment by mrrcomp** [comment]
![PaypalError](https://github.com/smartstore/Smartstore/assets/710257/66ae9599-655e-406e-9f16-5b462f2a4c04)

**Comment by mrrcomp** [comment]
hi
it seems when i try to add the paypal method on the second store the payment option doesnt even show???

Meir

**Comment by Michael-Herzog** [comment]
Hi,
I've just tested on store.mrrcomputers.cc. The script for the PayPal SDK can't probably not be loaded because of the currency NIS which is not supported by PayPal.
Regards,
Michael

**Comment by mrrcomp** [comment]
Hi

Thanks..
Firstly I do believe paypal supports israeli shekels I pay with that all the time??

Secondly  what about the fact that on the second store robinscreations.store the paypal payment option doesn’t show at all??

Regards

Meir

**Comment by Michael-Herzog** [comment]
_Secondly  what about the fact that on the second store robinscreations.store the paypal payment option doesn’t show at all??_ 

One problem at a time. 

Yes it's true PayPal supports Israeli new shekel:
https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/

But your currency has the ISO code NIS and not ILS.

Regards,

**Comment by mrrcomp** [comment]
HI again

I switched the currency code to ILS now the paypal works on the store.mrrcomputers.cc
but still only on that store not the robinscreations.store ??

Regards

Meir

**Comment by Michael-Herzog** [comment]
Right now you seem to have disabled PayPal in both stores. Please check if the PayPal method is disabled:
https://store.mrrcomputers.cc/admin/payment/edit/?systemName=Payments.PayPalStandard
Also check your multistore settings for the PayPal plugin:
https://store.mrrcomputers.cc/admin/paypal/configure/?returnUrl=%2Fadmin%2Fpayment%2Fproviders%2F

**Comment by mrrcomp** [comment]
HI
Thanks for taking your time to help me.

I didn’t disable I was able to go all the way on the store.mrrcomputers.cc to the paypal popup .. Check if the problem is that the paypal is not activated on first time you get to the payment choice.. ?

***@***.***


And I see the configurations for both stores with the correct email,client,secret

Regards

Meir

**Comment by Michael-Herzog** [comment]
Hi, 
the problem for me in the computer store, was that I expected the button in the offcanvas cart :-) On the payment selection page it was there. 

I've checked in different stores now, generally there's no problem in a multi store environment. So I've also checked the code. The only hint I have right now is the application cache. Can you please clear it (upper right corner in the admin area).

Regards,
Michael

**Comment by mrrcomp** [comment]
Believe or not the default admin user 👥/pwd work
________________________________

**Comment by Michael-Herzog** [comment]
I don't know if I understood this correctly. 
There is no default admin password combination in Smartstore. You're asked explicitly when installing to enter this data,

**Comment by mrrcomp** [comment]
I think I installed via the host company anyways yes 👍 register ilk et uu as admin
________________________________

**Comment by Michael-Herzog** [comment]
I've done it

**Comment by mrrcomp** [comment]
So have I 😊

Thanks for everything 😊

Meir\

**Comment by mrrcomp** [comment]
Hi 👋
Thanks.  I updated to 5.1 yesterday or day before.
Can you explain how you added the second store?
________________________________

**Comment by Michael-Herzog** [comment]
You're welcome! Just click on the link within the card in the link I've posted above.

**Comment by stefanmuellerdo** [comment]
(please close this issue if fixed, thanks)
