### ISSUE TITLE
In MediaGallery template, check if a handler for video files exists and render some kind of fallback if there is not

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#918]
Hi,

Preview picture does not appear in videos.

I thought it was caused by the video, so I tried it in the live demo. 
https://ibb.co/VtNKC45

When I try it on the current project, it looks like the picture. 
https://ibb.co/rQQkVZM

**Comment by markwoerdenweber** [comment]
This is what it looks like on my screen:

![productdetails-video-preview-small](https://github.com/smartstore/Smartstore/assets/116349750/8671c995-1679-4d94-b149-806357e1eba3)

After refreshing the page, the backend displayed the preview image.

**Comment by suatsuphi** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/wpWqrWs/ezgif-1-1e12824eb4.gif" alt="ezgif-1-1e12824eb4" border="0"></a>
I'm not working on hosting.
I run the project on visual studio

**Comment by suatsuphi** [comment]
<a href="https://ibb.co/VxvY5KB"><img src="https://i.ibb.co/sCF9zB3/Untitled.png" alt="Untitled" border="0"></a>

the image doesn't come from the url here. it is a video
http://localhost:44325/media/253/catalog/nakliye2.mp4?size=680

**Comment by markwoerdenweber** [comment]
It could be a problem caused by referencing an mp4 file in an img tag.
Could you test this in an independent context? Also, what browser are you using?

**Comment by suatsuphi** [comment]
https://github.com/smartstore/Smartstore 

1- I downloaded and ran the project 
2- SQL Server or SQLITE and Media storage= File System that I did the installation by selecting
3- I have attached any video to any product.

Can you please download it from github as a new project and try it?

**Comment by markwoerdenweber** [comment]
I could not reproduce the problem on a fresh installation either.
What browser are you using, and have you tested whether a simple HTML file containing an img tag with the src attribute pointing to an mp4 file will display the preview image correctly?

**Comment by suatsuphi** [comment]
<a href="https://ibb.co/6mwqbR4"><img src="https://i.ibb.co/NsCGp6L/Untitled.png" alt="Untitled" border="0"></a>

there is an error message where I marked 
slick-lazyload-error

**Comment by suatsuphi** [comment]
thumb images that occur when I upload images do not occur when I upload videos

**Comment by markwoerdenweber** [comment]
Automatic thumbnail generation for videos is an exclusive feature of Media Manager.

If you're interested, please contact sales@smartstore.com for more information.

**Comment by suatsuphi** [comment]
Can the bug at least be fixed, because the picture is not shown, but instead the video or the picture of the video icon can be shown? slick-lazyload-error

**Comment by muratcakir** [comment]
Please make sure that `mp4` is defined as valid video extension via **Configuration / Settings / Media / Media types / Video**.

However, without the **Media Manager** plugin you won't get a thumbnail, just an icon.

**Comment by suatsuphi** [comment]
<a href="https://ibb.co/Gv1VWqN"><img src="https://i.ibb.co/KjQ92JS/Untitled.png" alt="Untitled" border="0"></a>

>  However, without the Media Manager plugin you won't get a thumbnail, just an icon.

as you said, there is no need for a small image. just don't give an error, it gives an error that the image cannot be displayed. can the img tag be removed? the play button is enough 

<a href="https://ibb.co/5nppYXp"><img src="https://i.ibb.co/nndd3qd/Untitled2.png" alt="Untitled2" border="0"></a>

It gives error when img tag!

**Comment by suatsuphi** [comment]
can this problem be fixed? I made a patch like below.

Can it be added to [5.2.0](https://github.com/smartstore/Smartstore/milestone/11)?


MediaGallery.cshtml 


```
else
{
    <figure class="file-figure gal-item-content">
        <picture class="file-thumb show fs-display-3" data-type="video" title="@file.TitleAttribute">
            <img class="file-img d-none" attrs="@srcAttributes" alt="@file.Alt" />
            <video class="file-video" alt="@file.Alt" attrs="@srcAttributes">
                <source src="@file.GetUrl()" type="video/mp4">
            </video>
        </picture>
    </figure>
}


```

**Comment by suatsuphi** [comment]
```
  <figure class="file-figure gal-item-content">
      <picture class="file-thumb show fs-display-3" data-type="video" title="@file.TitleAttribute">
          <img class="gal-item-content d-none" src="@Model.FallbackUrl" alt="@Model.DefaultAlt" />
          <video class="file-img file-video" alt="@file.Alt" attrs="@srcAttributes">
              <source src="@file.GetUrl()" type="video/mp4">
          </video>
      </picture>
  </figure>
```

Can this section be fixed? I made a patch like this and it works fine! If I don't use the img tag, it gives an error like this.



Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')    at Object.getThumbBoundsFn (smartstore.gallery.js:531:48)    at PhotoSwipe.<anonymous> (photoswipe.js:2951:75)    at _shout (photoswipe.js:433:20)    at PhotoSwipe.init (photoswipe.js:891:6)    at HTMLAnchorElement.<anonymous> (smartstore.gallery.js:553:30)    at HTMLDivElement.dispatch (jquery-3.7.1.js:5145:27)    at elemData.handle (jquery-3.7.1.js:4949:28)

**Comment by muratcakir** [comment]
@markwoerdenweber Please review, check and apply fix.
