### ISSUE TITLE
Pagebuilder elements displayed in wrong order in the overview on the right side

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#925]
**Describe the bug**
If you make the screen a bit smaller then the active blocks are shown at the right side.
But they are in reverse order. The uppermost element is the last element on the page.

**To Reproduce**
1. Create a pagebuilder page
2. Add some elements (1st column top down: 2 text and one image)
3. Move the page width slide a bit to the left so you can see the active blocks of the page on the right
4. The image block will be the top element even if it is the last item on the page.

**Expected behavior**
Order should be Left to right, then top to bottom (or RTL for RTL languages)

**Comment by markwoerdenweber** [comment]
The block manager displays items in reverse z-index order. Top to bottom is highest to lowest value.

**Comment by Algorithman** [comment]
Oh, that's why you can move them around. Thanks for the info :)
