### ISSUE TITLE
Pagebuilder WebApi endpoints - Import/Export would be really nice

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#929]
**Is your feature request related to a problem? Please describe.**
Since I want to automate the backup of our stories I looked into the webapi endpoints of PageBuilder.
But since they're all seem to be internal only (via the StoryAdminController) I wonder how I could automate my daily backup.

My goal is to be able to get back up and running in at most a day after a catastrophic failure (meaning, no backups valid, no means to restore). Creating the stories takes quite some time, so I really would like to back them up separately.

So minimum requirements for this would be:
- Indexing (list of all stories, Id and systemname, maybe some additional info's like which page it is shown/zone assignment, published)
- Export
- Import

**Comment by stefanmuellerdo** [comment]
This is I great idea, I would like something like that in Web API even acces to the contents. But: To quote some recent discussions about that, it would be tough for a Page Builder (PB) user to manage PB Stories through the Web API. There are a lot of data with very specific formats. If there's a mistake, the story gets messed up. 

Exporting and importing stories as you requested seems like a much better and easier way to exchange them.

**Comment by Algorithman** [comment]
That's why I only asked for export/import and listing of the stories :)

**Comment by mgesing** [comment]
Resolved.
