### ISSUE TITLE
[Question] Possibility for Prices/surcharges for customer groups

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#944]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a surcharge for a specific customer group?
Since it is not a shipping surcharge but a surcharge on each product I can't use the shipping method.

Background: We need to increase the prices shown/calculated for US, Canada and Swiss customers since their customs duties are higher than elsewhere. But since it is based per product and not per shipping I wonder if there is a mechanism for this in Smartstore.

**Comment by mgesing** [comment]
The [Depending Prices module](https://community.smartstore.com/index.php?/files/file/210-depending-prices/) allows you to specify prices per customer group.

**Comment by Algorithman** [comment]
Thanks, i'll try it.
Quick suggestion: The downloads there are http only and chrome for example blocks a http download by default.
You might want to change that to https.
