### ISSUE TITLE
Close some customer menus Orders, Downloadable products, Back in stock subscriptions and My Orders with parameter

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#957]
Hi,
I wanna close some customer menu. these are Orders, Downloadable products, Back in stock subscriptions and My Orders 

Could a parameter be added to close these menus or can it be linked to an existing parameter?

![image](https://github.com/smartstore/Smartstore/assets/20780272/4d4c0f82-6593-40b2-9a68-32f6f56f6407)

![image](https://github.com/smartstore/Smartstore/assets/20780272/02550eac-ba12-4b3e-b3d0-ebe67004690f)

**Comment by mgesing** [comment]
See `CustomerSettings.HideDownloadableProductsTab` and `CustomerSettings.HideBackInStockSubscriptionsTab`. The order list cannot be hidden by setting. To do this, you must write an event handler for the `MenuBuiltEvent` event and remove it using `TreeNodeBase.Remove`.

**Comment by suatsuphi** [comment]
thank you.

Could a similar parameter be added in order?

**Comment by suatsuphi** [comment]
@mgesing 

When I close the shopping cart, the price on the product detail page also closes.... can we make the price section close only when the price is hidden? 


![image](https://github.com/smartstore/Smartstore/assets/20780272/4a066d80-8b48-46e1-8088-abb663df8f55)

**Comment by suatsuphi** [comment]
thank you @mgesing 

Could a similar parameter be added for Orders and My Orders?

**Comment by mgesing** [comment]
Did you mean customer settings? I wouldn't do that for an online store. We also have to think about reducing and the sense of so many settings. You can use the `MenuBuiltEvent` to hide it.

**Comment by suatsuphi** [comment]
> Did you mean customer settings?  

yes. I think this setting, which is there for others, should be there for this one too. 
like CustomerSettings.HideOrdersTabs

![image](https://github.com/smartstore/Smartstore/assets/20780272/30e94534-0e7d-4516-af9b-f3451b7a770d)

**Comment by suatsuphi** [comment]
or could you add parametre in permission. 

![image](https://github.com/smartstore/Smartstore/assets/20780272/bc46f6e9-506c-4d72-a459-5e7eb350bd9d)

I can even close wishlist but not orders.

**Comment by suatsuphi** [comment]
https://github.com/smartstore/Smartstore/pull/1034

access orders > 
If a parameter like here is not desired, can it be ensured that these three menus do not appear if the user does not have an order, downloadable and in stock subscription? I can destroy two of them with parameter but not possible for orders...  
orders.count > 0

**Comment by suatsuphi** [comment]
https://github.com/smartstore/Smartstore/issues/1150 

similar topic
