### ISSUE TITLE
SofortÜberweisung (Klarna)

### ISSUE THREAD

**Issue by schraufi** [smartstore/Smartstore#967]
For some orders with the payment method (SofortÜberweisung), no customer or order is created/displayed.

The invoice amount is debited from the customer's account and transferred correctly.

No order confirmation is sent to the customer.

Lg, Alex

**Comment by mgesing** [comment]
Is this for guests or registered customers?

**Comment by schraufi** [comment]
These must be **guest** orders because the customer is not created at all.

The money is debited from the customer but:
- no order
- no costumer
- no emails

Very annoying for me and the customer.

**Comment by schraufi** [comment]
I just checked again.
We also have **guests** where everything works. 🤔

We also recently had a “Paid” order where no money was debited from the customer and no transaction ID was transmitted.

**Comment by schraufi** [comment]
I have now **deactivated** the payment method.
Every second order is debited from the customer but not created.

**Comment by mgesing** [comment]
Klarna has discontinued "Sofortüberweisung" as an independent payment method (interface api.sofort.com). Payments via Smartstore.Sofortueberweisung are therefore no longer possible.
