### ISSUE TITLE
Implementation of Language-Neutral Links for Multilingual Support in Smartstore

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#987]
**Description:**
An issue has been identified where automatic translation of content (with a special tool) on multilingual Smartstore websites results in broken links when these are translated. This leads to a 404 error page, as the translated URLs do not correspond to actual paths on the server. This problem adversely affects the user experience. It is very time-consuming to fix links manually for each language.

**Feature Proposal:**
The implementation of a system for language-neutral links that are only converted into the user's language after the link is clicked.

**Advantages:**
- Elimination of 404 errors due to the automatic translation of URLs.
- Enhanced user experience through seamless navigation in the user’s preferred language.
- Preservation of SEO integrity across multilingual pages.

**Disadvantages:**
- Nomore SEO descriptive links

This feature would ensure a robust and reliable user experience on multilingual Smartstore websites while maintaining the integrity of links across different languages.

![allgemeiner-link](https://github.com/smartstore/Smartstore/assets/54363171/647e3ff4-a414-46de-9a78-6b86969098a7)

**Comment by muratcakir** [comment]
Actual links should never be translated by translators. Therefore, this is not an app issue, but a translation issue.
