### ISSUE TITLE
Dasboard full screen and news hide

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#999]
Hi,

could hide  news with a parameter and Dasboard full screen? 

![image](https://github.com/smartstore/Smartstore/assets/20780272/ecf7bb83-f049-40b8-939a-45b1db1be80c)

**Comment by Michael-Herzog** [comment]
What is the benefit of this?

**Comment by suatsuphi** [comment]
graphics and values look clearer. The intertwined chaos disappears.
